# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Z:\Darren\Python\EMCCD-psychic\mainWindow.ui'
#
# Created: Tue Feb 17 14:54:17 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(902, 880)
        MainWindow.setToolTip(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideRight)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabSettings = QtGui.QWidget()
        self.tabSettings.setObjectName(_fromUtf8("tabSettings"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tabSettings)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.groupBox_2 = QtGui.QGroupBox(self.tabSettings)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_6.setFlat(True)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_4.setContentsMargins(0, 10, 0, 0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.cSettingsADChannel = QtGui.QComboBox(self.groupBox_6)
        self.cSettingsADChannel.setObjectName(_fromUtf8("cSettingsADChannel"))
        self.verticalLayout_4.addWidget(self.cSettingsADChannel)
        self.gridLayout_2.addWidget(self.groupBox_6, 0, 0, 1, 1)
        self.groupBox_13 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_13.setFlat(True)
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.groupBox_13)
        self.horizontalLayout_11.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.cSettingsHSS = QtGui.QComboBox(self.groupBox_13)
        self.cSettingsHSS.setObjectName(_fromUtf8("cSettingsHSS"))
        self.horizontalLayout_11.addWidget(self.cSettingsHSS)
        self.gridLayout_2.addWidget(self.groupBox_13, 2, 1, 1, 1)
        self.groupBox_11 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_11.setFlat(True)
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.groupBox_11)
        self.horizontalLayout_9.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.cSettingsVSS = QtGui.QComboBox(self.groupBox_11)
        self.cSettingsVSS.setObjectName(_fromUtf8("cSettingsVSS"))
        self.horizontalLayout_9.addWidget(self.cSettingsVSS)
        self.gridLayout_2.addWidget(self.groupBox_11, 0, 1, 1, 1)
        self.groupBox_12 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_12.setFlat(True)
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.groupBox_12)
        self.horizontalLayout_10.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.cSettingsReadMode = QtGui.QComboBox(self.groupBox_12)
        self.cSettingsReadMode.setObjectName(_fromUtf8("cSettingsReadMode"))
        self.cSettingsReadMode.addItem(_fromUtf8(""))
        self.cSettingsReadMode.addItem(_fromUtf8(""))
        self.cSettingsReadMode.addItem(_fromUtf8(""))
        self.cSettingsReadMode.addItem(_fromUtf8(""))
        self.cSettingsReadMode.addItem(_fromUtf8(""))
        self.horizontalLayout_10.addWidget(self.cSettingsReadMode)
        self.gridLayout_2.addWidget(self.groupBox_12, 2, 0, 1, 1)
        self.groupBox_14 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_14.setFlat(True)
        self.groupBox_14.setObjectName(_fromUtf8("groupBox_14"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.groupBox_14)
        self.horizontalLayout_12.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.cSettingsTrigger = QtGui.QComboBox(self.groupBox_14)
        self.cSettingsTrigger.setObjectName(_fromUtf8("cSettingsTrigger"))
        self.cSettingsTrigger.addItem(_fromUtf8(""))
        self.cSettingsTrigger.addItem(_fromUtf8(""))
        self.horizontalLayout_12.addWidget(self.cSettingsTrigger)
        self.gridLayout_2.addWidget(self.groupBox_14, 3, 0, 1, 1)
        self.groupBox_15 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_15.setFlat(True)
        self.groupBox_15.setObjectName(_fromUtf8("groupBox_15"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.groupBox_15)
        self.horizontalLayout_13.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.cSettingsAcquisitionMode = QtGui.QComboBox(self.groupBox_15)
        self.cSettingsAcquisitionMode.setObjectName(_fromUtf8("cSettingsAcquisitionMode"))
        self.cSettingsAcquisitionMode.addItem(_fromUtf8(""))
        self.cSettingsAcquisitionMode.addItem(_fromUtf8(""))
        self.cSettingsAcquisitionMode.addItem(_fromUtf8(""))
        self.cSettingsAcquisitionMode.addItem(_fromUtf8(""))
        self.cSettingsAcquisitionMode.addItem(_fromUtf8(""))
        self.cSettingsAcquisitionMode.addItem(_fromUtf8(""))
        self.cSettingsAcquisitionMode.addItem(_fromUtf8(""))
        self.cSettingsAcquisitionMode.addItem(_fromUtf8(""))
        self.cSettingsAcquisitionMode.addItem(_fromUtf8(""))
        self.cSettingsAcquisitionMode.addItem(_fromUtf8(""))
        self.horizontalLayout_13.addWidget(self.cSettingsAcquisitionMode)
        self.gridLayout_2.addWidget(self.groupBox_15, 3, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        self.gbImageParams = QtGui.QGroupBox(self.groupBox_2)
        self.gbImageParams.setEnabled(True)
        self.gbImageParams.setObjectName(_fromUtf8("gbImageParams"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.gbImageParams)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.groupBox_18 = QtGui.QGroupBox(self.gbImageParams)
        self.groupBox_18.setFlat(True)
        self.groupBox_18.setObjectName(_fromUtf8("groupBox_18"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.groupBox_18)
        self.horizontalLayout_16.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.tHStart = QINumberEdit(self.groupBox_18)
        self.tHStart.setObjectName(_fromUtf8("tHStart"))
        self.horizontalLayout_16.addWidget(self.tHStart)
        self.gridLayout_4.addWidget(self.groupBox_18, 0, 1, 1, 1)
        self.groupBox_17 = QtGui.QGroupBox(self.gbImageParams)
        self.groupBox_17.setFlat(True)
        self.groupBox_17.setObjectName(_fromUtf8("groupBox_17"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.groupBox_17)
        self.horizontalLayout_15.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.tVBin = QINumberEdit(self.groupBox_17)
        self.tVBin.setObjectName(_fromUtf8("tVBin"))
        self.horizontalLayout_15.addWidget(self.tVBin)
        self.gridLayout_4.addWidget(self.groupBox_17, 2, 0, 1, 1)
        self.groupBox_16 = QtGui.QGroupBox(self.gbImageParams)
        self.groupBox_16.setFlat(True)
        self.groupBox_16.setObjectName(_fromUtf8("groupBox_16"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.groupBox_16)
        self.horizontalLayout_14.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.tHBin = QINumberEdit(self.groupBox_16)
        self.tHBin.setObjectName(_fromUtf8("tHBin"))
        self.horizontalLayout_14.addWidget(self.tHBin)
        self.gridLayout_4.addWidget(self.groupBox_16, 0, 0, 1, 1)
        self.groupBox_19 = QtGui.QGroupBox(self.gbImageParams)
        self.groupBox_19.setFlat(True)
        self.groupBox_19.setObjectName(_fromUtf8("groupBox_19"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.groupBox_19)
        self.horizontalLayout_17.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.tHEnd = QINumberEdit(self.groupBox_19)
        self.tHEnd.setObjectName(_fromUtf8("tHEnd"))
        self.horizontalLayout_17.addWidget(self.tHEnd)
        self.gridLayout_4.addWidget(self.groupBox_19, 0, 2, 1, 1)
        self.groupBox_20 = QtGui.QGroupBox(self.gbImageParams)
        self.groupBox_20.setFlat(True)
        self.groupBox_20.setObjectName(_fromUtf8("groupBox_20"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout(self.groupBox_20)
        self.horizontalLayout_18.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.tVStart = QINumberEdit(self.groupBox_20)
        self.tVStart.setObjectName(_fromUtf8("tVStart"))
        self.horizontalLayout_18.addWidget(self.tVStart)
        self.gridLayout_4.addWidget(self.groupBox_20, 2, 1, 1, 1)
        self.groupBox_21 = QtGui.QGroupBox(self.gbImageParams)
        self.groupBox_21.setFlat(True)
        self.groupBox_21.setObjectName(_fromUtf8("groupBox_21"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout(self.groupBox_21)
        self.horizontalLayout_19.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.tVEnd = QINumberEdit(self.groupBox_21)
        self.tVEnd.setObjectName(_fromUtf8("tVEnd"))
        self.horizontalLayout_19.addWidget(self.tVEnd)
        self.gridLayout_4.addWidget(self.groupBox_21, 2, 2, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_4)
        self.verticalLayout_5.addWidget(self.gbImageParams)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.bSettingsApply = QtGui.QPushButton(self.groupBox_2)
        self.bSettingsApply.setObjectName(_fromUtf8("bSettingsApply"))
        self.horizontalLayout_3.addWidget(self.bSettingsApply)
        self.bSettingsCancel = QtGui.QPushButton(self.groupBox_2)
        self.bSettingsCancel.setObjectName(_fromUtf8("bSettingsCancel"))
        self.horizontalLayout_3.addWidget(self.bSettingsCancel)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_7.addWidget(self.groupBox_2)
        self.groupBox_5 = QtGui.QGroupBox(self.tabSettings)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_8.setFlat(True)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_8.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.tBackgroundName = QtGui.QLineEdit(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tBackgroundName.sizePolicy().hasHeightForWidth())
        self.tBackgroundName.setSizePolicy(sizePolicy)
        self.tBackgroundName.setObjectName(_fromUtf8("tBackgroundName"))
        self.horizontalLayout_8.addWidget(self.tBackgroundName)
        self.horizontalLayout_7.addWidget(self.groupBox_8)
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_7.setFlat(True)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_6.setContentsMargins(0, 10, 0, 0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.tImageName = QtGui.QLineEdit(self.groupBox_7)
        self.tImageName.setObjectName(_fromUtf8("tImageName"))
        self.verticalLayout_6.addWidget(self.tImageName)
        self.horizontalLayout_7.addWidget(self.groupBox_7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.groupBox_9 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_9.setFlat(True)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_5.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.tSettingsBGDirectory = QtGui.QLineEdit(self.groupBox_9)
        self.tSettingsBGDirectory.setObjectName(_fromUtf8("tSettingsBGDirectory"))
        self.horizontalLayout_5.addWidget(self.tSettingsBGDirectory)
        self.bSettingsBGDirectory = QtGui.QPushButton(self.groupBox_9)
        self.bSettingsBGDirectory.setObjectName(_fromUtf8("bSettingsBGDirectory"))
        self.horizontalLayout_5.addWidget(self.bSettingsBGDirectory)
        self.verticalLayout_3.addWidget(self.groupBox_9)
        self.groupBox_10 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_10.setFlat(True)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBox_10)
        self.horizontalLayout_6.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.tSettingsIMGDirectory = QtGui.QLineEdit(self.groupBox_10)
        self.tSettingsIMGDirectory.setObjectName(_fromUtf8("tSettingsIMGDirectory"))
        self.horizontalLayout_6.addWidget(self.tSettingsIMGDirectory)
        self.bSettingsIMGDirectory = QtGui.QPushButton(self.groupBox_10)
        self.bSettingsIMGDirectory.setObjectName(_fromUtf8("bSettingsIMGDirectory"))
        self.horizontalLayout_6.addWidget(self.bSettingsIMGDirectory)
        self.verticalLayout_3.addWidget(self.groupBox_10)
        self.verticalLayout_7.addWidget(self.groupBox_5)
        self.groupBox_3 = QtGui.QGroupBox(self.tabSettings)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.groupBox_22 = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox_22.setFlat(True)
        self.groupBox_22.setObjectName(_fromUtf8("groupBox_22"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout(self.groupBox_22)
        self.horizontalLayout_20.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.tSettingsCurrTemp = QtGui.QLineEdit(self.groupBox_22)
        self.tSettingsCurrTemp.setReadOnly(True)
        self.tSettingsCurrTemp.setObjectName(_fromUtf8("tSettingsCurrTemp"))
        self.horizontalLayout_20.addWidget(self.tSettingsCurrTemp)
        self.horizontalLayout_4.addWidget(self.groupBox_22)
        self.groupBox_23 = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox_23.setFlat(True)
        self.groupBox_23.setObjectName(_fromUtf8("groupBox_23"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout(self.groupBox_23)
        self.horizontalLayout_21.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.tSettingsGotoTemp = QINumberEdit(self.groupBox_23)
        self.tSettingsGotoTemp.setObjectName(_fromUtf8("tSettingsGotoTemp"))
        self.horizontalLayout_21.addWidget(self.tSettingsGotoTemp)
        self.horizontalLayout_4.addWidget(self.groupBox_23)
        self.bSetTemp = QtGui.QPushButton(self.groupBox_3)
        self.bSetTemp.setObjectName(_fromUtf8("bSetTemp"))
        self.horizontalLayout_4.addWidget(self.bSetTemp)
        self.groupBox_24 = QtGui.QGroupBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_24.sizePolicy().hasHeightForWidth())
        self.groupBox_24.setSizePolicy(sizePolicy)
        self.groupBox_24.setFlat(True)
        self.groupBox_24.setObjectName(_fromUtf8("groupBox_24"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout(self.groupBox_24)
        self.horizontalLayout_22.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.tSettingsTempResponse = QtGui.QLineEdit(self.groupBox_24)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tSettingsTempResponse.sizePolicy().hasHeightForWidth())
        self.tSettingsTempResponse.setSizePolicy(sizePolicy)
        self.tSettingsTempResponse.setReadOnly(True)
        self.tSettingsTempResponse.setObjectName(_fromUtf8("tSettingsTempResponse"))
        self.horizontalLayout_22.addWidget(self.tSettingsTempResponse)
        self.horizontalLayout_4.addWidget(self.groupBox_24)
        self.verticalLayout_7.addWidget(self.groupBox_3)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.tabWidget.addTab(self.tabSettings, _fromUtf8(""))
        self.tabEMCCD = QtGui.QWidget()
        self.tabEMCCD.setObjectName(_fromUtf8("tabEMCCD"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.tabEMCCD)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_35 = QtGui.QHBoxLayout()
        self.horizontalLayout_35.setObjectName(_fromUtf8("horizontalLayout_35"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox_35 = QtGui.QGroupBox(self.tabEMCCD)
        self.groupBox_35.setFlat(True)
        self.groupBox_35.setObjectName(_fromUtf8("groupBox_35"))
        self.horizontalLayout_33 = QtGui.QHBoxLayout(self.groupBox_35)
        self.horizontalLayout_33.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_33.setObjectName(_fromUtf8("horizontalLayout_33"))
        self.tEMCCDGain = QINumberEdit(self.groupBox_35)
        self.tEMCCDGain.setObjectName(_fromUtf8("tEMCCDGain"))
        self.horizontalLayout_33.addWidget(self.tEMCCDGain)
        self.gridLayout.addWidget(self.groupBox_35, 4, 1, 1, 1)
        self.groupBox_37 = QtGui.QGroupBox(self.tabEMCCD)
        self.groupBox_37.setFlat(True)
        self.groupBox_37.setCheckable(False)
        self.groupBox_37.setObjectName(_fromUtf8("groupBox_37"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_37)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setContentsMargins(0, 10, 0, 0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.tCCDImageNum = QINumberEdit(self.groupBox_37)
        self.tCCDImageNum.setObjectName(_fromUtf8("tCCDImageNum"))
        self.gridLayout_7.addWidget(self.tCCDImageNum, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_37, 3, 2, 1, 1)
        self.groupBox_34 = QtGui.QGroupBox(self.tabEMCCD)
        self.groupBox_34.setFlat(True)
        self.groupBox_34.setObjectName(_fromUtf8("groupBox_34"))
        self.horizontalLayout_32 = QtGui.QHBoxLayout(self.groupBox_34)
        self.horizontalLayout_32.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
        self.tEMCCDExp = QFNumberEdit(self.groupBox_34)
        self.tEMCCDExp.setObjectName(_fromUtf8("tEMCCDExp"))
        self.horizontalLayout_32.addWidget(self.tEMCCDExp)
        self.gridLayout.addWidget(self.groupBox_34, 3, 1, 1, 1)
        self.groupBox_38 = QtGui.QGroupBox(self.tabEMCCD)
        self.groupBox_38.setFlat(True)
        self.groupBox_38.setCheckable(False)
        self.groupBox_38.setObjectName(_fromUtf8("groupBox_38"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_38)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setContentsMargins(0, 10, 0, 0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.tCCDBGNum = QINumberEdit(self.groupBox_38)
        self.tCCDBGNum.setObjectName(_fromUtf8("tCCDBGNum"))
        self.gridLayout_8.addWidget(self.tCCDBGNum, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_38, 4, 2, 1, 1)
        self.groupBox_36 = QtGui.QGroupBox(self.tabEMCCD)
        self.groupBox_36.setFlat(True)
        self.groupBox_36.setCheckable(False)
        self.groupBox_36.setObjectName(_fromUtf8("groupBox_36"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_36)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setContentsMargins(0, 10, 0, 0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.tCCDNIRwavelength = QtGui.QLineEdit(self.groupBox_36)
        self.tCCDNIRwavelength.setObjectName(_fromUtf8("tCCDNIRwavelength"))
        self.gridLayout_6.addWidget(self.tCCDNIRwavelength, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_36, 0, 1, 1, 1)
        self.groupBox_45 = QtGui.QGroupBox(self.tabEMCCD)
        self.groupBox_45.setFlat(True)
        self.groupBox_45.setCheckable(False)
        self.groupBox_45.setObjectName(_fromUtf8("groupBox_45"))
        self.gridLayout_15 = QtGui.QGridLayout(self.groupBox_45)
        self.gridLayout_15.setSpacing(0)
        self.gridLayout_15.setContentsMargins(0, 10, 0, 0)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.tCCDSlits = QtGui.QLineEdit(self.groupBox_45)
        self.tCCDSlits.setObjectName(_fromUtf8("tCCDSlits"))
        self.gridLayout_15.addWidget(self.tCCDSlits, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_45, 2, 0, 1, 1)
        self.groupBox_40 = QtGui.QGroupBox(self.tabEMCCD)
        self.groupBox_40.setFlat(True)
        self.groupBox_40.setCheckable(False)
        self.groupBox_40.setObjectName(_fromUtf8("groupBox_40"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox_40)
        self.gridLayout_10.setSpacing(0)
        self.gridLayout_10.setContentsMargins(0, 10, 0, 0)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.tCCDFELP = QtGui.QLineEdit(self.groupBox_40)
        self.tCCDFELP.setObjectName(_fromUtf8("tCCDFELP"))
        self.gridLayout_10.addWidget(self.tCCDFELP, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_40, 1, 1, 1, 1)
        self.bCCDBack = QtGui.QPushButton(self.tabEMCCD)
        self.bCCDBack.setObjectName(_fromUtf8("bCCDBack"))
        self.gridLayout.addWidget(self.bCCDBack, 4, 0, 1, 1)
        self.groupBox_41 = QtGui.QGroupBox(self.tabEMCCD)
        self.groupBox_41.setFlat(True)
        self.groupBox_41.setCheckable(False)
        self.groupBox_41.setObjectName(_fromUtf8("groupBox_41"))
        self.gridLayout_11 = QtGui.QGridLayout(self.groupBox_41)
        self.gridLayout_11.setSpacing(0)
        self.gridLayout_11.setContentsMargins(0, 10, 0, 0)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.tCCDFELRR = QtGui.QLineEdit(self.groupBox_41)
        self.tCCDFELRR.setObjectName(_fromUtf8("tCCDFELRR"))
        self.gridLayout_11.addWidget(self.tCCDFELRR, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_41, 1, 2, 1, 1)
        self.bCCDImage = QtGui.QPushButton(self.tabEMCCD)
        self.bCCDImage.setObjectName(_fromUtf8("bCCDImage"))
        self.gridLayout.addWidget(self.bCCDImage, 3, 0, 1, 1)
        self.groupBox_44 = QtGui.QGroupBox(self.tabEMCCD)
        self.groupBox_44.setFlat(True)
        self.groupBox_44.setCheckable(False)
        self.groupBox_44.setObjectName(_fromUtf8("groupBox_44"))
        self.gridLayout_14 = QtGui.QGridLayout(self.groupBox_44)
        self.gridLayout_14.setSpacing(0)
        self.gridLayout_14.setContentsMargins(0, 10, 0, 0)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.tCCDYMax = QtGui.QLineEdit(self.groupBox_44)
        self.tCCDYMax.setObjectName(_fromUtf8("tCCDYMax"))
        self.gridLayout_14.addWidget(self.tCCDYMax, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_44, 2, 2, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.tabEMCCD)
        self.groupBox_4.setFlat(True)
        self.groupBox_4.setCheckable(False)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setContentsMargins(0, 10, 0, 0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tCCDNIRP = QtGui.QLineEdit(self.groupBox_4)
        self.tCCDNIRP.setObjectName(_fromUtf8("tCCDNIRP"))
        self.gridLayout_3.addWidget(self.tCCDNIRP, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.groupBox_39 = QtGui.QGroupBox(self.tabEMCCD)
        self.groupBox_39.setFlat(True)
        self.groupBox_39.setCheckable(False)
        self.groupBox_39.setObjectName(_fromUtf8("groupBox_39"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_39)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setContentsMargins(0, 10, 0, 0)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.tCCDFELFreq = QtGui.QLineEdit(self.groupBox_39)
        self.tCCDFELFreq.setObjectName(_fromUtf8("tCCDFELFreq"))
        self.gridLayout_9.addWidget(self.tCCDFELFreq, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_39, 1, 0, 1, 1)
        self.groupBox_43 = QtGui.QGroupBox(self.tabEMCCD)
        self.groupBox_43.setFlat(True)
        self.groupBox_43.setCheckable(False)
        self.groupBox_43.setObjectName(_fromUtf8("groupBox_43"))
        self.gridLayout_13 = QtGui.QGridLayout(self.groupBox_43)
        self.gridLayout_13.setSpacing(0)
        self.gridLayout_13.setContentsMargins(0, 10, 0, 0)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.tCCDYMin = QtGui.QLineEdit(self.groupBox_43)
        self.tCCDYMin.setObjectName(_fromUtf8("tCCDYMin"))
        self.gridLayout_13.addWidget(self.tCCDYMin, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_43, 2, 1, 1, 1)
        self.groupBox_42 = QtGui.QGroupBox(self.tabEMCCD)
        self.groupBox_42.setFlat(True)
        self.groupBox_42.setCheckable(False)
        self.groupBox_42.setObjectName(_fromUtf8("groupBox_42"))
        self.gridLayout_12 = QtGui.QGridLayout(self.groupBox_42)
        self.gridLayout_12.setSpacing(0)
        self.gridLayout_12.setContentsMargins(0, 10, 0, 0)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.tCCDSeries = QtGui.QLineEdit(self.groupBox_42)
        self.tCCDSeries.setStatusTip(_fromUtf8(""))
        self.tCCDSeries.setWhatsThis(_fromUtf8(""))
        self.tCCDSeries.setAccessibleName(_fromUtf8(""))
        self.tCCDSeries.setAccessibleDescription(_fromUtf8(""))
        self.tCCDSeries.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tCCDSeries.setText(_fromUtf8(""))
        self.tCCDSeries.setObjectName(_fromUtf8("tCCDSeries"))
        self.gridLayout_12.addWidget(self.tCCDSeries, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_42, 0, 2, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout)
        self.groupBox_46 = QtGui.QGroupBox(self.tabEMCCD)
        self.groupBox_46.setFlat(True)
        self.groupBox_46.setObjectName(_fromUtf8("groupBox_46"))
        self.horizontalLayout_37 = QtGui.QHBoxLayout(self.groupBox_46)
        self.horizontalLayout_37.setObjectName(_fromUtf8("horizontalLayout_37"))
        self.tCCDComments = QtGui.QTextEdit(self.groupBox_46)
        self.tCCDComments.setObjectName(_fromUtf8("tCCDComments"))
        self.horizontalLayout_37.addWidget(self.tCCDComments)
        self.verticalLayout_9.addWidget(self.groupBox_46)
        self.verticalLayout_9.setStretch(1, 1)
        self.horizontalLayout_35.addLayout(self.verticalLayout_9)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.gCCDImage = GraphicsLayoutWidget(self.tabEMCCD)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gCCDImage.sizePolicy().hasHeightForWidth())
        self.gCCDImage.setSizePolicy(sizePolicy)
        self.gCCDImage.setObjectName(_fromUtf8("gCCDImage"))
        self.verticalLayout_8.addWidget(self.gCCDImage)
        self.gCCDBack = GraphicsLayoutWidget(self.tabEMCCD)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gCCDBack.sizePolicy().hasHeightForWidth())
        self.gCCDBack.setSizePolicy(sizePolicy)
        self.gCCDBack.setObjectName(_fromUtf8("gCCDBack"))
        self.verticalLayout_8.addWidget(self.gCCDBack)
        self.verticalLayout_8.setStretch(0, 1)
        self.verticalLayout_8.setStretch(1, 1)
        self.horizontalLayout_35.addLayout(self.verticalLayout_8)
        self.horizontalLayout_35.setStretch(1, 1)
        self.verticalLayout_10.addLayout(self.horizontalLayout_35)
        self.gCCDBin = PlotWidget(self.tabEMCCD)
        self.gCCDBin.setObjectName(_fromUtf8("gCCDBin"))
        self.verticalLayout_10.addWidget(self.gCCDBin)
        self.horizontalLayout_34 = QtGui.QHBoxLayout()
        self.horizontalLayout_34.setObjectName(_fromUtf8("horizontalLayout_34"))
        self.pCCD = QtGui.QProgressBar(self.tabEMCCD)
        self.pCCD.setProperty("value", 0)
        self.pCCD.setObjectName(_fromUtf8("pCCD"))
        self.horizontalLayout_34.addWidget(self.pCCD)
        self.lCCDProg = QtGui.QLabel(self.tabEMCCD)
        self.lCCDProg.setObjectName(_fromUtf8("lCCDProg"))
        self.horizontalLayout_34.addWidget(self.lCCDProg)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem2)
        self.verticalLayout_10.addLayout(self.horizontalLayout_34)
        self.tabWidget.addTab(self.tabEMCCD, _fromUtf8(""))
        self.tabSpec = QtGui.QWidget()
        self.tabSpec.setObjectName(_fromUtf8("tabSpec"))
        self.groupBox_33 = QtGui.QGroupBox(self.tabSpec)
        self.groupBox_33.setGeometry(QtCore.QRect(420, 370, 105, 71))
        self.groupBox_33.setFlat(True)
        self.groupBox_33.setObjectName(_fromUtf8("groupBox_33"))
        self.horizontalLayout_31 = QtGui.QHBoxLayout(self.groupBox_33)
        self.horizontalLayout_31.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.sbSpecWavelength = QtGui.QDoubleSpinBox(self.groupBox_33)
        self.sbSpecWavelength.setSpecialValueText(_fromUtf8(""))
        self.sbSpecWavelength.setMaximum(1200.0)
        self.sbSpecWavelength.setObjectName(_fromUtf8("sbSpecWavelength"))
        self.horizontalLayout_31.addWidget(self.sbSpecWavelength)
        self.bSpecSet = QtGui.QPushButton(self.tabSpec)
        self.bSpecSet.setGeometry(QtCore.QRect(539, 412, 111, 20))
        self.bSpecSet.setObjectName(_fromUtf8("bSpecSet"))
        self.groupBox = QtGui.QGroupBox(self.tabSpec)
        self.groupBox.setGeometry(QtCore.QRect(300, 480, 83, 71))
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_36 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_36.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_36.setObjectName(_fromUtf8("horizontalLayout_36"))
        self.sbSpecGrating = QtGui.QSpinBox(self.groupBox)
        self.sbSpecGrating.setMinimum(1)
        self.sbSpecGrating.setMaximum(2)
        self.sbSpecGrating.setObjectName(_fromUtf8("sbSpecGrating"))
        self.horizontalLayout_36.addWidget(self.sbSpecGrating)
        self.tabWidget.addTab(self.tabSpec, _fromUtf8(""))
        self.tabOsc = QtGui.QWidget()
        self.tabOsc.setObjectName(_fromUtf8("tabOsc"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabOsc)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gOsc = PlotWidget(self.tabOsc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gOsc.sizePolicy().hasHeightForWidth())
        self.gOsc.setSizePolicy(sizePolicy)
        self.gOsc.setObjectName(_fromUtf8("gOsc"))
        self.verticalLayout_2.addWidget(self.gOsc)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.groupBox_25 = QtGui.QGroupBox(self.tabOsc)
        self.groupBox_25.setFlat(True)
        self.groupBox_25.setObjectName(_fromUtf8("groupBox_25"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout(self.groupBox_25)
        self.horizontalLayout_23.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.tBgSt = QFNumberEdit(self.groupBox_25)
        self.tBgSt.setText(_fromUtf8(""))
        self.tBgSt.setObjectName(_fromUtf8("tBgSt"))
        self.horizontalLayout_23.addWidget(self.tBgSt)
        self.gridLayout_5.addWidget(self.groupBox_25, 0, 0, 1, 1)
        self.groupBox_27 = QtGui.QGroupBox(self.tabOsc)
        self.groupBox_27.setFlat(True)
        self.groupBox_27.setObjectName(_fromUtf8("groupBox_27"))
        self.horizontalLayout_25 = QtGui.QHBoxLayout(self.groupBox_27)
        self.horizontalLayout_25.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.tFpSt = QFNumberEdit(self.groupBox_27)
        self.tFpSt.setObjectName(_fromUtf8("tFpSt"))
        self.horizontalLayout_25.addWidget(self.tFpSt)
        self.gridLayout_5.addWidget(self.groupBox_27, 0, 1, 1, 1)
        self.groupBox_29 = QtGui.QGroupBox(self.tabOsc)
        self.groupBox_29.setFlat(True)
        self.groupBox_29.setObjectName(_fromUtf8("groupBox_29"))
        self.horizontalLayout_27 = QtGui.QHBoxLayout(self.groupBox_29)
        self.horizontalLayout_27.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.tCdSt = QFNumberEdit(self.groupBox_29)
        self.tCdSt.setObjectName(_fromUtf8("tCdSt"))
        self.horizontalLayout_27.addWidget(self.tCdSt)
        self.gridLayout_5.addWidget(self.groupBox_29, 0, 2, 1, 1)
        self.groupBox_26 = QtGui.QGroupBox(self.tabOsc)
        self.groupBox_26.setFlat(True)
        self.groupBox_26.setObjectName(_fromUtf8("groupBox_26"))
        self.horizontalLayout_24 = QtGui.QHBoxLayout(self.groupBox_26)
        self.horizontalLayout_24.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.tBgEn = QFNumberEdit(self.groupBox_26)
        self.tBgEn.setText(_fromUtf8(""))
        self.tBgEn.setObjectName(_fromUtf8("tBgEn"))
        self.horizontalLayout_24.addWidget(self.tBgEn)
        self.gridLayout_5.addWidget(self.groupBox_26, 1, 0, 1, 1)
        self.groupBox_28 = QtGui.QGroupBox(self.tabOsc)
        self.groupBox_28.setFlat(True)
        self.groupBox_28.setObjectName(_fromUtf8("groupBox_28"))
        self.horizontalLayout_26 = QtGui.QHBoxLayout(self.groupBox_28)
        self.horizontalLayout_26.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.tFpEn = QFNumberEdit(self.groupBox_28)
        self.tFpEn.setObjectName(_fromUtf8("tFpEn"))
        self.horizontalLayout_26.addWidget(self.tFpEn)
        self.gridLayout_5.addWidget(self.groupBox_28, 1, 1, 1, 1)
        self.groupBox_30 = QtGui.QGroupBox(self.tabOsc)
        self.groupBox_30.setFlat(True)
        self.groupBox_30.setObjectName(_fromUtf8("groupBox_30"))
        self.horizontalLayout_28 = QtGui.QHBoxLayout(self.groupBox_30)
        self.horizontalLayout_28.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.tCdEn = QFNumberEdit(self.groupBox_30)
        self.tCdEn.setObjectName(_fromUtf8("tCdEn"))
        self.horizontalLayout_28.addWidget(self.tCdEn)
        self.gridLayout_5.addWidget(self.groupBox_30, 1, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_5)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.bOPause = QtGui.QPushButton(self.tabOsc)
        self.bOPause.setCheckable(True)
        self.bOPause.setChecked(True)
        self.bOPause.setObjectName(_fromUtf8("bOPause"))
        self.horizontalLayout.addWidget(self.bOPause)
        self.groupBox_31 = QtGui.QGroupBox(self.tabOsc)
        self.groupBox_31.setFlat(True)
        self.groupBox_31.setObjectName(_fromUtf8("groupBox_31"))
        self.horizontalLayout_29 = QtGui.QHBoxLayout(self.groupBox_31)
        self.horizontalLayout_29.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.cOGPIB = QtGui.QComboBox(self.groupBox_31)
        self.cOGPIB.setObjectName(_fromUtf8("cOGPIB"))
        self.horizontalLayout_29.addWidget(self.cOGPIB)
        self.horizontalLayout.addWidget(self.groupBox_31)
        self.groupBox_32 = QtGui.QGroupBox(self.tabOsc)
        self.groupBox_32.setFlat(True)
        self.groupBox_32.setObjectName(_fromUtf8("groupBox_32"))
        self.horizontalLayout_30 = QtGui.QHBoxLayout(self.groupBox_32)
        self.horizontalLayout_30.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.cOChannel = QtGui.QComboBox(self.groupBox_32)
        self.cOChannel.setObjectName(_fromUtf8("cOChannel"))
        self.cOChannel.addItem(_fromUtf8(""))
        self.cOChannel.addItem(_fromUtf8(""))
        self.cOChannel.addItem(_fromUtf8(""))
        self.cOChannel.addItem(_fromUtf8(""))
        self.horizontalLayout_30.addWidget(self.cOChannel)
        self.horizontalLayout.addWidget(self.groupBox_32)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.bOPop = QtGui.QPushButton(self.tabOsc)
        self.bOPop.setObjectName(_fromUtf8("bOPop"))
        self.horizontalLayout.addWidget(self.bOPop)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tabOsc, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 902, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.cSettingsReadMode.setCurrentIndex(4)
        self.cSettingsAcquisitionMode.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.cSettingsADChannel, self.cSettingsVSS)
        MainWindow.setTabOrder(self.cSettingsVSS, self.cSettingsReadMode)
        MainWindow.setTabOrder(self.cSettingsReadMode, self.cSettingsHSS)
        MainWindow.setTabOrder(self.cSettingsHSS, self.cSettingsTrigger)
        MainWindow.setTabOrder(self.cSettingsTrigger, self.cSettingsAcquisitionMode)
        MainWindow.setTabOrder(self.cSettingsAcquisitionMode, self.tHBin)
        MainWindow.setTabOrder(self.tHBin, self.tHStart)
        MainWindow.setTabOrder(self.tHStart, self.tHEnd)
        MainWindow.setTabOrder(self.tHEnd, self.tVBin)
        MainWindow.setTabOrder(self.tVBin, self.tVStart)
        MainWindow.setTabOrder(self.tVStart, self.tVEnd)
        MainWindow.setTabOrder(self.tVEnd, self.bSettingsApply)
        MainWindow.setTabOrder(self.bSettingsApply, self.bSettingsCancel)
        MainWindow.setTabOrder(self.bSettingsCancel, self.tBackgroundName)
        MainWindow.setTabOrder(self.tBackgroundName, self.tImageName)
        MainWindow.setTabOrder(self.tImageName, self.tSettingsBGDirectory)
        MainWindow.setTabOrder(self.tSettingsBGDirectory, self.bSettingsBGDirectory)
        MainWindow.setTabOrder(self.bSettingsBGDirectory, self.tSettingsIMGDirectory)
        MainWindow.setTabOrder(self.tSettingsIMGDirectory, self.bSettingsIMGDirectory)
        MainWindow.setTabOrder(self.bSettingsIMGDirectory, self.tSettingsCurrTemp)
        MainWindow.setTabOrder(self.tSettingsCurrTemp, self.tSettingsGotoTemp)
        MainWindow.setTabOrder(self.tSettingsGotoTemp, self.bSetTemp)
        MainWindow.setTabOrder(self.bSetTemp, self.tSettingsTempResponse)
        MainWindow.setTabOrder(self.tSettingsTempResponse, self.tCCDNIRP)
        MainWindow.setTabOrder(self.tCCDNIRP, self.tCCDNIRwavelength)
        MainWindow.setTabOrder(self.tCCDNIRwavelength, self.tCCDSeries)
        MainWindow.setTabOrder(self.tCCDSeries, self.tCCDFELFreq)
        MainWindow.setTabOrder(self.tCCDFELFreq, self.tCCDFELP)
        MainWindow.setTabOrder(self.tCCDFELP, self.tCCDFELRR)
        MainWindow.setTabOrder(self.tCCDFELRR, self.tCCDSlits)
        MainWindow.setTabOrder(self.tCCDSlits, self.tCCDYMin)
        MainWindow.setTabOrder(self.tCCDYMin, self.tCCDYMax)
        MainWindow.setTabOrder(self.tCCDYMax, self.bCCDImage)
        MainWindow.setTabOrder(self.bCCDImage, self.tEMCCDExp)
        MainWindow.setTabOrder(self.tEMCCDExp, self.tCCDImageNum)
        MainWindow.setTabOrder(self.tCCDImageNum, self.bCCDBack)
        MainWindow.setTabOrder(self.bCCDBack, self.tEMCCDGain)
        MainWindow.setTabOrder(self.tEMCCDGain, self.tCCDBGNum)
        MainWindow.setTabOrder(self.tCCDBGNum, self.tCCDComments)
        MainWindow.setTabOrder(self.tCCDComments, self.tCdEn)
        MainWindow.setTabOrder(self.tCdEn, self.bOPause)
        MainWindow.setTabOrder(self.bOPause, self.cOGPIB)
        MainWindow.setTabOrder(self.cOGPIB, self.cOChannel)
        MainWindow.setTabOrder(self.cOChannel, self.bOPop)
        MainWindow.setTabOrder(self.bOPop, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.tBgSt)
        MainWindow.setTabOrder(self.tBgSt, self.tBgEn)
        MainWindow.setTabOrder(self.tBgEn, self.gCCDBack)
        MainWindow.setTabOrder(self.gCCDBack, self.gOsc)
        MainWindow.setTabOrder(self.gOsc, self.tFpSt)
        MainWindow.setTabOrder(self.tFpSt, self.gCCDImage)
        MainWindow.setTabOrder(self.gCCDImage, self.sbSpecWavelength)
        MainWindow.setTabOrder(self.sbSpecWavelength, self.bSpecSet)
        MainWindow.setTabOrder(self.bSpecSet, self.tCdSt)
        MainWindow.setTabOrder(self.tCdSt, self.gCCDBin)
        MainWindow.setTabOrder(self.gCCDBin, self.tFpEn)
        MainWindow.setTabOrder(self.tFpEn, self.sbSpecGrating)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "EMCCD", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "CCD Settings", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "AD Channel", None))
        self.groupBox_13.setTitle(_translate("MainWindow", "Horizontal Speed", None))
        self.groupBox_11.setTitle(_translate("MainWindow", "Vertical Speed", None))
        self.groupBox_12.setTitle(_translate("MainWindow", "Read Mode", None))
        self.cSettingsReadMode.setItemText(0, _translate("MainWindow", "Full Vertical Binning", None))
        self.cSettingsReadMode.setItemText(1, _translate("MainWindow", "Multi-Track", None))
        self.cSettingsReadMode.setItemText(2, _translate("MainWindow", "Random-Track", None))
        self.cSettingsReadMode.setItemText(3, _translate("MainWindow", "Single-Track", None))
        self.cSettingsReadMode.setItemText(4, _translate("MainWindow", "Image", None))
        self.groupBox_14.setTitle(_translate("MainWindow", "Trigger Type", None))
        self.cSettingsTrigger.setItemText(0, _translate("MainWindow", "Internal", None))
        self.cSettingsTrigger.setItemText(1, _translate("MainWindow", "External", None))
        self.groupBox_15.setTitle(_translate("MainWindow", "Acquisition Mode", None))
        self.cSettingsAcquisitionMode.setItemText(0, _translate("MainWindow", "NA", None))
        self.cSettingsAcquisitionMode.setItemText(1, _translate("MainWindow", "Single Scan", None))
        self.cSettingsAcquisitionMode.setItemText(2, _translate("MainWindow", "Accumulate", None))
        self.cSettingsAcquisitionMode.setItemText(3, _translate("MainWindow", "Kinetic", None))
        self.cSettingsAcquisitionMode.setItemText(4, _translate("MainWindow", "Fast Kinetics", None))
        self.cSettingsAcquisitionMode.setItemText(5, _translate("MainWindow", "Run till abort", None))
        self.cSettingsAcquisitionMode.setItemText(6, _translate("MainWindow", "NA", None))
        self.cSettingsAcquisitionMode.setItemText(7, _translate("MainWindow", "NA", None))
        self.cSettingsAcquisitionMode.setItemText(8, _translate("MainWindow", "NA", None))
        self.cSettingsAcquisitionMode.setItemText(9, _translate("MainWindow", "Time delayed integration", None))
        self.gbImageParams.setTitle(_translate("MainWindow", "Image Parameters", None))
        self.groupBox_18.setTitle(_translate("MainWindow", "Horizontal Start", None))
        self.groupBox_17.setTitle(_translate("MainWindow", "Vertical Binning", None))
        self.groupBox_16.setTitle(_translate("MainWindow", "Horizontal Binning", None))
        self.groupBox_19.setTitle(_translate("MainWindow", "Horizontal End", None))
        self.groupBox_20.setTitle(_translate("MainWindow", "Vertical Start", None))
        self.groupBox_21.setTitle(_translate("MainWindow", "Vertical End", None))
        self.bSettingsApply.setText(_translate("MainWindow", "Apply", None))
        self.bSettingsCancel.setText(_translate("MainWindow", "Cancel", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Save settings", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Background Name", None))
        self.tBackgroundName.setText(_translate("MainWindow", "test", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Image Name", None))
        self.tImageName.setText(_translate("MainWindow", "tesyu", None))
        self.groupBox_9.setTitle(_translate("MainWindow", "Background Directory", None))
        self.bSettingsBGDirectory.setText(_translate("MainWindow", "Choose..", None))
        self.groupBox_10.setTitle(_translate("MainWindow", "Image Directory", None))
        self.bSettingsIMGDirectory.setText(_translate("MainWindow", "Choose..", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Temperature Control", None))
        self.groupBox_22.setTitle(_translate("MainWindow", "Current Temp", None))
        self.tSettingsCurrTemp.setText(_translate("MainWindow", "20", None))
        self.groupBox_23.setTitle(_translate("MainWindow", "Desired Temp", None))
        self.bSetTemp.setText(_translate("MainWindow", "Set Temperature", None))
        self.groupBox_24.setTitle(_translate("MainWindow", "Response", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSettings), _translate("MainWindow", "Settings", None))
        self.groupBox_35.setTitle(_translate("MainWindow", "Gain", None))
        self.tEMCCDGain.setText(_translate("MainWindow", "1", None))
        self.groupBox_37.setTitle(_translate("MainWindow", "Image Number", None))
        self.tCCDImageNum.setText(_translate("MainWindow", "0", None))
        self.groupBox_34.setTitle(_translate("MainWindow", "Exposure (s)", None))
        self.tEMCCDExp.setText(_translate("MainWindow", "0.5", None))
        self.groupBox_38.setTitle(_translate("MainWindow", "Background Number", None))
        self.tCCDBGNum.setText(_translate("MainWindow", "0", None))
        self.groupBox_36.setTitle(_translate("MainWindow", "NIR Wavelength (nm)", None))
        self.tCCDNIRwavelength.setText(_translate("MainWindow", "0", None))
        self.groupBox_45.setTitle(_translate("MainWindow", "Slits", None))
        self.tCCDSlits.setText(_translate("MainWindow", "0", None))
        self.groupBox_40.setTitle(_translate("MainWindow", "FEL Power", None))
        self.tCCDFELP.setText(_translate("MainWindow", "0", None))
        self.bCCDBack.setText(_translate("MainWindow", "Take Background", None))
        self.groupBox_41.setTitle(_translate("MainWindow", "Rep Rate (s)", None))
        self.tCCDFELRR.setText(_translate("MainWindow", "0.75", None))
        self.bCCDImage.setText(_translate("MainWindow", "Take Image", None))
        self.groupBox_44.setTitle(_translate("MainWindow", "Ymax", None))
        self.tCCDYMax.setText(_translate("MainWindow", "400", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "NIR Power (mw)", None))
        self.tCCDNIRP.setText(_translate("MainWindow", "0", None))
        self.groupBox_39.setTitle(_translate("MainWindow", "FEL Freq (GHz)", None))
        self.tCCDFELFreq.setText(_translate("MainWindow", "0", None))
        self.groupBox_43.setTitle(_translate("MainWindow", "Ymin", None))
        self.tCCDYMin.setText(_translate("MainWindow", "0", None))
        self.groupBox_42.setTitle(_translate("MainWindow", "Series", None))
        self.tCCDSeries.setToolTip(_translate("MainWindow", "NIRP, NIRW, FELF, FELP, SLITS", None))
        self.groupBox_46.setTitle(_translate("MainWindow", "Comments", None))
        self.lCCDProg.setText(_translate("MainWindow", "Done.", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabEMCCD), _translate("MainWindow", "EMCCD", None))
        self.groupBox_33.setTitle(_translate("MainWindow", "Center wavelength", None))
        self.bSpecSet.setText(_translate("MainWindow", "Set", None))
        self.groupBox.setTitle(_translate("MainWindow", "Grating", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSpec), _translate("MainWindow", "Spectrometer", None))
        self.groupBox_25.setTitle(_translate("MainWindow", "Background Start", None))
        self.groupBox_27.setTitle(_translate("MainWindow", "Front Porch Start", None))
        self.groupBox_29.setTitle(_translate("MainWindow", "Cavity Dump Start", None))
        self.groupBox_26.setTitle(_translate("MainWindow", "Background End", None))
        self.groupBox_28.setTitle(_translate("MainWindow", "Front Porch End", None))
        self.groupBox_30.setTitle(_translate("MainWindow", "Cavity Dump End", None))
        self.bOPause.setText(_translate("MainWindow", "Pause", None))
        self.groupBox_31.setTitle(_translate("MainWindow", "GPIB", None))
        self.groupBox_32.setTitle(_translate("MainWindow", "Channel", None))
        self.cOChannel.setItemText(0, _translate("MainWindow", "1", None))
        self.cOChannel.setItemText(1, _translate("MainWindow", "2", None))
        self.cOChannel.setItemText(2, _translate("MainWindow", "3", None))
        self.cOChannel.setItemText(3, _translate("MainWindow", "4", None))
        self.bOPop.setText(_translate("MainWindow", "Pop Out", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabOsc), _translate("MainWindow", "Oscilloscope", None))

from customQt import QINumberEdit, QFNumberEdit
from pyqtgraph import PlotWidget, GraphicsLayoutWidget
