# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Public\Documents\Github\EMCCD-Regensburg\UIs\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1198, 1239)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/test/icon.jpg"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolTip("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideRight)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tabSettings = QtWidgets.QWidget()
        self.tabSettings.setObjectName("tabSettings")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tabSettings)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gbSettings = QtWidgets.QGroupBox(self.tabSettings)
        self.gbSettings.setObjectName("gbSettings")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.gbSettings)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_6 = QtWidgets.QGroupBox(self.gbSettings)
        self.groupBox_6.setFlat(True)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_4.setContentsMargins(0, 10, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.cSettingsADChannel = QtWidgets.QComboBox(self.groupBox_6)
        self.cSettingsADChannel.setObjectName("cSettingsADChannel")
        self.verticalLayout_4.addWidget(self.cSettingsADChannel)
        self.gridLayout_2.addWidget(self.groupBox_6, 0, 0, 1, 1)
        self.groupBox_13 = QtWidgets.QGroupBox(self.gbSettings)
        self.groupBox_13.setFlat(True)
        self.groupBox_13.setObjectName("groupBox_13")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.groupBox_13)
        self.horizontalLayout_11.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.cSettingsHSS = QtWidgets.QComboBox(self.groupBox_13)
        self.cSettingsHSS.setObjectName("cSettingsHSS")
        self.horizontalLayout_11.addWidget(self.cSettingsHSS)
        self.gridLayout_2.addWidget(self.groupBox_13, 2, 1, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(self.gbSettings)
        self.groupBox_11.setFlat(True)
        self.groupBox_11.setObjectName("groupBox_11")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_11)
        self.horizontalLayout_9.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.cSettingsVSS = QtWidgets.QComboBox(self.groupBox_11)
        self.cSettingsVSS.setObjectName("cSettingsVSS")
        self.horizontalLayout_9.addWidget(self.cSettingsVSS)
        self.gridLayout_2.addWidget(self.groupBox_11, 0, 1, 1, 1)
        self.groupBox_12 = QtWidgets.QGroupBox(self.gbSettings)
        self.groupBox_12.setFlat(True)
        self.groupBox_12.setObjectName("groupBox_12")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.groupBox_12)
        self.horizontalLayout_10.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.cSettingsReadMode = QtWidgets.QComboBox(self.groupBox_12)
        self.cSettingsReadMode.setEnabled(False)
        self.cSettingsReadMode.setObjectName("cSettingsReadMode")
        self.cSettingsReadMode.addItem("")
        self.cSettingsReadMode.addItem("")
        self.cSettingsReadMode.addItem("")
        self.cSettingsReadMode.addItem("")
        self.cSettingsReadMode.addItem("")
        self.horizontalLayout_10.addWidget(self.cSettingsReadMode)
        self.gridLayout_2.addWidget(self.groupBox_12, 2, 0, 1, 1)
        self.groupBox_14 = QtWidgets.QGroupBox(self.gbSettings)
        self.groupBox_14.setFlat(True)
        self.groupBox_14.setObjectName("groupBox_14")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.groupBox_14)
        self.horizontalLayout_12.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.cSettingsTrigger = QtWidgets.QComboBox(self.groupBox_14)
        self.cSettingsTrigger.setObjectName("cSettingsTrigger")
        self.cSettingsTrigger.addItem("")
        self.cSettingsTrigger.addItem("")
        self.horizontalLayout_12.addWidget(self.cSettingsTrigger)
        self.gridLayout_2.addWidget(self.groupBox_14, 3, 0, 1, 1)
        self.groupBox_15 = QtWidgets.QGroupBox(self.gbSettings)
        self.groupBox_15.setFlat(True)
        self.groupBox_15.setObjectName("groupBox_15")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.groupBox_15)
        self.horizontalLayout_13.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.cSettingsAcquisitionMode = QtWidgets.QComboBox(self.groupBox_15)
        self.cSettingsAcquisitionMode.setEnabled(False)
        self.cSettingsAcquisitionMode.setObjectName("cSettingsAcquisitionMode")
        self.cSettingsAcquisitionMode.addItem("")
        self.cSettingsAcquisitionMode.addItem("")
        self.cSettingsAcquisitionMode.addItem("")
        self.cSettingsAcquisitionMode.addItem("")
        self.cSettingsAcquisitionMode.addItem("")
        self.cSettingsAcquisitionMode.addItem("")
        self.cSettingsAcquisitionMode.addItem("")
        self.cSettingsAcquisitionMode.addItem("")
        self.cSettingsAcquisitionMode.addItem("")
        self.cSettingsAcquisitionMode.addItem("")
        self.horizontalLayout_13.addWidget(self.cSettingsAcquisitionMode)
        self.gridLayout_2.addWidget(self.groupBox_15, 3, 1, 1, 1)
        self.groupBox_50 = QtWidgets.QGroupBox(self.gbSettings)
        self.groupBox_50.setFlat(True)
        self.groupBox_50.setObjectName("groupBox_50")
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout(self.groupBox_50)
        self.horizontalLayout_42.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.cSettingsShutterEx = QtWidgets.QComboBox(self.groupBox_50)
        self.cSettingsShutterEx.setObjectName("cSettingsShutterEx")
        self.cSettingsShutterEx.addItem("")
        self.cSettingsShutterEx.addItem("")
        self.cSettingsShutterEx.addItem("")
        self.horizontalLayout_42.addWidget(self.cSettingsShutterEx)
        self.gridLayout_2.addWidget(self.groupBox_50, 4, 1, 1, 1)
        self.groupBox_51 = QtWidgets.QGroupBox(self.gbSettings)
        self.groupBox_51.setFlat(True)
        self.groupBox_51.setObjectName("groupBox_51")
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout(self.groupBox_51)
        self.horizontalLayout_43.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.cSettingsShutter = QtWidgets.QComboBox(self.groupBox_51)
        self.cSettingsShutter.setEnabled(False)
        self.cSettingsShutter.setObjectName("cSettingsShutter")
        self.cSettingsShutter.addItem("")
        self.cSettingsShutter.addItem("")
        self.cSettingsShutter.addItem("")
        self.horizontalLayout_43.addWidget(self.cSettingsShutter)
        self.gridLayout_2.addWidget(self.groupBox_51, 4, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        self.gbImageParams = QtWidgets.QGroupBox(self.gbSettings)
        self.gbImageParams.setEnabled(True)
        self.gbImageParams.setObjectName("gbImageParams")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.gbImageParams)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_18 = QtWidgets.QGroupBox(self.gbImageParams)
        self.groupBox_18.setFlat(True)
        self.groupBox_18.setObjectName("groupBox_18")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.groupBox_18)
        self.horizontalLayout_16.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.tHStart = QINumberEdit(self.groupBox_18)
        self.tHStart.setEnabled(False)
        self.tHStart.setObjectName("tHStart")
        self.horizontalLayout_16.addWidget(self.tHStart)
        self.gridLayout_4.addWidget(self.groupBox_18, 0, 1, 1, 1)
        self.groupBox_17 = QtWidgets.QGroupBox(self.gbImageParams)
        self.groupBox_17.setFlat(True)
        self.groupBox_17.setObjectName("groupBox_17")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.groupBox_17)
        self.horizontalLayout_15.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.tVBin = QINumberEdit(self.groupBox_17)
        self.tVBin.setEnabled(True)
        self.tVBin.setObjectName("tVBin")
        self.horizontalLayout_15.addWidget(self.tVBin)
        self.gridLayout_4.addWidget(self.groupBox_17, 2, 0, 1, 1)
        self.groupBox_16 = QtWidgets.QGroupBox(self.gbImageParams)
        self.groupBox_16.setFlat(True)
        self.groupBox_16.setObjectName("groupBox_16")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.groupBox_16)
        self.horizontalLayout_14.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.tHBin = QINumberEdit(self.groupBox_16)
        self.tHBin.setEnabled(False)
        self.tHBin.setObjectName("tHBin")
        self.horizontalLayout_14.addWidget(self.tHBin)
        self.gridLayout_4.addWidget(self.groupBox_16, 0, 0, 1, 1)
        self.groupBox_19 = QtWidgets.QGroupBox(self.gbImageParams)
        self.groupBox_19.setFlat(True)
        self.groupBox_19.setObjectName("groupBox_19")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.groupBox_19)
        self.horizontalLayout_17.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.tHEnd = QINumberEdit(self.groupBox_19)
        self.tHEnd.setEnabled(True)
        self.tHEnd.setObjectName("tHEnd")
        self.horizontalLayout_17.addWidget(self.tHEnd)
        self.gridLayout_4.addWidget(self.groupBox_19, 0, 2, 1, 1)
        self.groupBox_20 = QtWidgets.QGroupBox(self.gbImageParams)
        self.groupBox_20.setFlat(True)
        self.groupBox_20.setObjectName("groupBox_20")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.groupBox_20)
        self.horizontalLayout_18.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.tVStart = QINumberEdit(self.groupBox_20)
        self.tVStart.setObjectName("tVStart")
        self.horizontalLayout_18.addWidget(self.tVStart)
        self.gridLayout_4.addWidget(self.groupBox_20, 2, 1, 1, 1)
        self.groupBox_21 = QtWidgets.QGroupBox(self.gbImageParams)
        self.groupBox_21.setFlat(True)
        self.groupBox_21.setObjectName("groupBox_21")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.groupBox_21)
        self.horizontalLayout_19.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.tVEnd = QINumberEdit(self.groupBox_21)
        self.tVEnd.setObjectName("tVEnd")
        self.horizontalLayout_19.addWidget(self.tVEnd)
        self.gridLayout_4.addWidget(self.groupBox_21, 2, 2, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_4)
        self.verticalLayout_5.addWidget(self.gbImageParams)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.bSettingsApply = QtWidgets.QPushButton(self.gbSettings)
        self.bSettingsApply.setObjectName("bSettingsApply")
        self.horizontalLayout_3.addWidget(self.bSettingsApply)
        self.bSettingsCancel = QtWidgets.QPushButton(self.gbSettings)
        self.bSettingsCancel.setObjectName("bSettingsCancel")
        self.horizontalLayout_3.addWidget(self.bSettingsCancel)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_7.addWidget(self.gbSettings)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tabSettings)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_8.setFlat(True)
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_8.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.tBackgroundName = MCLineEdit(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tBackgroundName.sizePolicy().hasHeightForWidth())
        self.tBackgroundName.setSizePolicy(sizePolicy)
        self.tBackgroundName.setObjectName("tBackgroundName")
        self.horizontalLayout_8.addWidget(self.tBackgroundName)
        self.horizontalLayout_7.addWidget(self.groupBox_8)
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_7.setFlat(True)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_6.setContentsMargins(0, 10, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tImageName = QtWidgets.QLineEdit(self.groupBox_7)
        self.tImageName.setObjectName("tImageName")
        self.verticalLayout_6.addWidget(self.tImageName)
        self.horizontalLayout_7.addWidget(self.groupBox_7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_9.setFlat(True)
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_5.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tSettingsDirectory = QtWidgets.QLineEdit(self.groupBox_9)
        self.tSettingsDirectory.setObjectName("tSettingsDirectory")
        self.horizontalLayout_5.addWidget(self.tSettingsDirectory)
        self.bSettingsDirectory = QtWidgets.QPushButton(self.groupBox_9)
        self.bSettingsDirectory.setObjectName("bSettingsDirectory")
        self.horizontalLayout_5.addWidget(self.bSettingsDirectory)
        self.verticalLayout_3.addWidget(self.groupBox_9)
        self.verticalLayout_7.addWidget(self.groupBox_5)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tabSettings)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_22 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_22.setFlat(True)
        self.groupBox_22.setObjectName("groupBox_22")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.groupBox_22)
        self.horizontalLayout_20.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.tSettingsCurrTemp = QtWidgets.QLineEdit(self.groupBox_22)
        self.tSettingsCurrTemp.setReadOnly(True)
        self.tSettingsCurrTemp.setObjectName("tSettingsCurrTemp")
        self.horizontalLayout_20.addWidget(self.tSettingsCurrTemp)
        self.horizontalLayout_4.addWidget(self.groupBox_22)
        self.groupBox_23 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_23.setFlat(True)
        self.groupBox_23.setObjectName("groupBox_23")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.groupBox_23)
        self.horizontalLayout_21.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.tSettingsGotoTemp = QINumberEdit(self.groupBox_23)
        self.tSettingsGotoTemp.setObjectName("tSettingsGotoTemp")
        self.horizontalLayout_21.addWidget(self.tSettingsGotoTemp)
        self.horizontalLayout_4.addWidget(self.groupBox_23)
        self.bSetTemp = QtWidgets.QPushButton(self.groupBox_3)
        self.bSetTemp.setObjectName("bSetTemp")
        self.horizontalLayout_4.addWidget(self.bSetTemp)
        self.groupBox_24 = QtWidgets.QGroupBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_24.sizePolicy().hasHeightForWidth())
        self.groupBox_24.setSizePolicy(sizePolicy)
        self.groupBox_24.setFlat(True)
        self.groupBox_24.setObjectName("groupBox_24")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.groupBox_24)
        self.horizontalLayout_22.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.tSettingsTempResponse = QtWidgets.QLineEdit(self.groupBox_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tSettingsTempResponse.sizePolicy().hasHeightForWidth())
        self.tSettingsTempResponse.setSizePolicy(sizePolicy)
        self.tSettingsTempResponse.setReadOnly(True)
        self.tSettingsTempResponse.setObjectName("tSettingsTempResponse")
        self.horizontalLayout_22.addWidget(self.tSettingsTempResponse)
        self.horizontalLayout_4.addWidget(self.groupBox_24)
        self.verticalLayout_7.addWidget(self.groupBox_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.tabWidget.addTab(self.tabSettings, "")
        self.tabSpec = QtWidgets.QWidget()
        self.tabSpec.setObjectName("tabSpec")
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout(self.tabSpec)
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem2, 0, 5, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tabSpec)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tSpecStartNM = QtWidgets.QLineEdit(self.groupBox_2)
        self.tSpecStartNM.setEnabled(False)
        self.tSpecStartNM.setObjectName("tSpecStartNM")
        self.horizontalLayout.addWidget(self.tSpecStartNM)
        self.gridLayout_16.addWidget(self.groupBox_2, 0, 3, 1, 1)
        self.bSpecSetGr = QtWidgets.QPushButton(self.tabSpec)
        self.bSpecSetGr.setObjectName("bSpecSetGr")
        self.gridLayout_16.addWidget(self.bSpecSetGr, 2, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tabSpec)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_36.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.sbSpecGrating = QtWidgets.QSpinBox(self.groupBox)
        self.sbSpecGrating.setMinimum(1)
        self.sbSpecGrating.setMaximum(3)
        self.sbSpecGrating.setObjectName("sbSpecGrating")
        self.horizontalLayout_36.addWidget(self.sbSpecGrating)
        self.gridLayout_16.addWidget(self.groupBox, 2, 0, 1, 1)
        self.groupBox_47 = QtWidgets.QGroupBox(self.tabSpec)
        self.groupBox_47.setFlat(True)
        self.groupBox_47.setObjectName("groupBox_47")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout(self.groupBox_47)
        self.horizontalLayout_38.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.tSpecCurWl = QtWidgets.QLineEdit(self.groupBox_47)
        self.tSpecCurWl.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tSpecCurWl.sizePolicy().hasHeightForWidth())
        self.tSpecCurWl.setSizePolicy(sizePolicy)
        self.tSpecCurWl.setObjectName("tSpecCurWl")
        self.horizontalLayout_38.addWidget(self.tSpecCurWl)
        self.gridLayout_16.addWidget(self.groupBox_47, 0, 2, 1, 1)
        self.bSpecSetWl = QtWidgets.QPushButton(self.tabSpec)
        self.bSpecSetWl.setObjectName("bSpecSetWl")
        self.gridLayout_16.addWidget(self.bSpecSetWl, 0, 1, 1, 1)
        self.groupBox_49 = QtWidgets.QGroupBox(self.tabSpec)
        self.groupBox_49.setFlat(True)
        self.groupBox_49.setObjectName("groupBox_49")
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout(self.groupBox_49)
        self.horizontalLayout_41.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.cSpecGPIB = InstrumentGPIB(self.groupBox_49)
        self.cSpecGPIB.setObjectName("cSpecGPIB")
        self.horizontalLayout_41.addWidget(self.cSpecGPIB)
        self.gridLayout_16.addWidget(self.groupBox_49, 3, 0, 1, 1)
        self.groupBox_33 = QtWidgets.QGroupBox(self.tabSpec)
        self.groupBox_33.setFlat(True)
        self.groupBox_33.setObjectName("groupBox_33")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.groupBox_33)
        self.horizontalLayout_31.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.sbSpecWavelength = QtWidgets.QDoubleSpinBox(self.groupBox_33)
        self.sbSpecWavelength.setSpecialValueText("")
        self.sbSpecWavelength.setMaximum(1200.0)
        self.sbSpecWavelength.setObjectName("sbSpecWavelength")
        self.horizontalLayout_31.addWidget(self.sbSpecWavelength)
        self.gridLayout_16.addWidget(self.groupBox_33, 0, 0, 1, 1)
        self.groupBox_48 = QtWidgets.QGroupBox(self.tabSpec)
        self.groupBox_48.setFlat(True)
        self.groupBox_48.setObjectName("groupBox_48")
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout(self.groupBox_48)
        self.horizontalLayout_39.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.tSpecCurGr = QtWidgets.QLineEdit(self.groupBox_48)
        self.tSpecCurGr.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tSpecCurGr.sizePolicy().hasHeightForWidth())
        self.tSpecCurGr.setSizePolicy(sizePolicy)
        self.tSpecCurGr.setObjectName("tSpecCurGr")
        self.horizontalLayout_39.addWidget(self.tSpecCurGr)
        self.gridLayout_16.addWidget(self.groupBox_48, 2, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem3, 4, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tabSpec)
        self.groupBox_4.setFlat(True)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_6.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.tSpecEndNM = QtWidgets.QLineEdit(self.groupBox_4)
        self.tSpecEndNM.setEnabled(False)
        self.tSpecEndNM.setObjectName("tSpecEndNM")
        self.horizontalLayout_6.addWidget(self.tSpecEndNM)
        self.gridLayout_16.addWidget(self.groupBox_4, 0, 4, 1, 1)
        self.gbSpecStartSB = QtWidgets.QGroupBox(self.tabSpec)
        self.gbSpecStartSB.setFlat(True)
        self.gbSpecStartSB.setObjectName("gbSpecStartSB")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.gbSpecStartSB)
        self.horizontalLayout_23.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.tSpecStartSB = QtWidgets.QLineEdit(self.gbSpecStartSB)
        self.tSpecStartSB.setEnabled(False)
        self.tSpecStartSB.setObjectName("tSpecStartSB")
        self.horizontalLayout_23.addWidget(self.tSpecStartSB)
        self.gridLayout_16.addWidget(self.gbSpecStartSB, 2, 3, 1, 1)
        self.gbSpecEndSB = QtWidgets.QGroupBox(self.tabSpec)
        self.gbSpecEndSB.setFlat(True)
        self.gbSpecEndSB.setObjectName("gbSpecEndSB")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.gbSpecEndSB)
        self.horizontalLayout_24.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.tSpecEndSB = QtWidgets.QLineEdit(self.gbSpecEndSB)
        self.tSpecEndSB.setEnabled(False)
        self.tSpecEndSB.setObjectName("tSpecEndSB")
        self.horizontalLayout_24.addWidget(self.tSpecEndSB)
        self.gridLayout_16.addWidget(self.gbSpecEndSB, 2, 4, 1, 1)
        self.horizontalLayout_40.addLayout(self.gridLayout_16)
        self.tabWidget.addTab(self.tabSpec, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.miscToolsLayout = QtWidgets.QVBoxLayout()
        self.miscToolsLayout.setObjectName("miscToolsLayout")
        self.verticalLayout_8.addLayout(self.miscToolsLayout)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1198, 38))
        self.menubar.setObjectName("menubar")
        self.menuOther_Settings = QtWidgets.QMenu(self.menubar)
        self.menuOther_Settings.setObjectName("menuOther_Settings")
        self.menuSweeps = QtWidgets.QMenu(self.menuOther_Settings)
        self.menuSweeps.setObjectName("menuSweeps")
        self.menuLive_Series = QtWidgets.QMenu(self.menubar)
        self.menuLive_Series.setObjectName("menuLive_Series")
        self.menuExperiment_Type = QtWidgets.QMenu(self.menubar)
        self.menuExperiment_Type.setObjectName("menuExperiment_Type")
        self.menuHSG_FVB = QtWidgets.QMenu(self.menuExperiment_Type)
        self.menuHSG_FVB.setObjectName("menuHSG_FVB")
        self.menuLive_Plots = QtWidgets.QMenu(self.menubar)
        self.menuLive_Plots.setObjectName("menuLive_Plots")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.mFileDoCRR = QtWidgets.QAction(MainWindow)
        self.mFileDoCRR.setCheckable(True)
        self.mFileDoCRR.setChecked(False)
        self.mFileDoCRR.setObjectName("mFileDoCRR")
        self.mFileBreakTemp = QtWidgets.QAction(MainWindow)
        self.mFileBreakTemp.setEnabled(False)
        self.mFileBreakTemp.setObjectName("mFileBreakTemp")
        self.mFileTakeContinuous = QtWidgets.QAction(MainWindow)
        self.mFileTakeContinuous.setCheckable(True)
        self.mFileTakeContinuous.setObjectName("mFileTakeContinuous")
        self.actionValue = QtWidgets.QAction(MainWindow)
        self.actionValue.setObjectName("actionValue")
        self.mFileEnableAll = QtWidgets.QAction(MainWindow)
        self.mFileEnableAll.setCheckable(True)
        self.mFileEnableAll.setObjectName("mFileEnableAll")
        self.mFileSumSpectraUndo = QtWidgets.QAction(MainWindow)
        self.mFileSumSpectraUndo.setObjectName("mFileSumSpectraUndo")
        self.mSeriesSum = QtWidgets.QAction(MainWindow)
        self.mSeriesSum.setCheckable(True)
        self.mSeriesSum.setChecked(True)
        self.mSeriesSum.setObjectName("mSeriesSum")
        self.mSeriesUndo = QtWidgets.QAction(MainWindow)
        self.mSeriesUndo.setEnabled(False)
        self.mSeriesUndo.setObjectName("mSeriesUndo")
        self.fExpTypeHSGImage = QtWidgets.QAction(MainWindow)
        self.fExpTypeHSGImage.setCheckable(True)
        self.fExpTypeHSGImage.setChecked(False)
        self.fExpTypeHSGImage.setObjectName("fExpTypeHSGImage")
        self.fExpTypePL = QtWidgets.QAction(MainWindow)
        self.fExpTypePL.setCheckable(True)
        self.fExpTypePL.setObjectName("fExpTypePL")
        self.fExpTypeAbs = QtWidgets.QAction(MainWindow)
        self.fExpTypeAbs.setCheckable(True)
        self.fExpTypeAbs.setObjectName("fExpTypeAbs")
        self.mFileFastExit = QtWidgets.QAction(MainWindow)
        self.mFileFastExit.setObjectName("mFileFastExit")
        self.fExpTypeTwo_Color_Abs = QtWidgets.QAction(MainWindow)
        self.fExpTypeTwo_Color_Abs.setCheckable(True)
        self.fExpTypeTwo_Color_Abs.setObjectName("fExpTypeTwo_Color_Abs")
        self.mLivePlotsDisableHistogramAutoscale = QtWidgets.QAction(MainWindow)
        self.mLivePlotsDisableHistogramAutoscale.setCheckable(True)
        self.mLivePlotsDisableHistogramAutoscale.setObjectName("mLivePlotsDisableHistogramAutoscale")
        self.mLivePlotsDisableRawPlots = QtWidgets.QAction(MainWindow)
        self.mLivePlotsDisableRawPlots.setCheckable(True)
        self.mLivePlotsDisableRawPlots.setObjectName("mLivePlotsDisableRawPlots")
        self.mRemoveImageSequence = QtWidgets.QAction(MainWindow)
        self.mRemoveImageSequence.setObjectName("mRemoveImageSequence")
        self.m = QtWidgets.QAction(MainWindow)
        self.m.setStatusTip("")
        self.m.setObjectName("m")
        self.fExpTypeAlignment = QtWidgets.QAction(MainWindow)
        self.fExpTypeAlignment.setCheckable(True)
        self.fExpTypeAlignment.setObjectName("fExpTypeAlignment")
        self.mLivePlotsForceAutoscale = QtWidgets.QAction(MainWindow)
        self.mLivePlotsForceAutoscale.setObjectName("mLivePlotsForceAutoscale")
        self.fExpTypeHSG_FVB = QtWidgets.QAction(MainWindow)
        self.fExpTypeHSG_FVB.setCheckable(True)
        self.fExpTypeHSG_FVB.setObjectName("fExpTypeHSG_FVB")
        self.fExpTypeHSG_Image = QtWidgets.QAction(MainWindow)
        self.fExpTypeHSG_Image.setCheckable(True)
        self.fExpTypeHSG_Image.setChecked(True)
        self.fExpTypeHSG_Image.setObjectName("fExpTypeHSG_Image")
        self.fExpTypeHSG_PhotonCounting = QtWidgets.QAction(MainWindow)
        self.fExpTypeHSG_PhotonCounting.setCheckable(True)
        self.fExpTypeHSG_PhotonCounting.setObjectName("fExpTypeHSG_PhotonCounting")
        self.mFileDoSpecSweep = QtWidgets.QAction(MainWindow)
        self.mFileDoSpecSweep.setObjectName("mFileDoSpecSweep")
        self.mFileScanNeLines = QtWidgets.QAction(MainWindow)
        self.mFileScanNeLines.setObjectName("mFileScanNeLines")
        self.mFileOpenDebugConsole = QtWidgets.QAction(MainWindow)
        self.mFileOpenDebugConsole.setObjectName("mFileOpenDebugConsole")
        self.mRemoveBackgroundSequence = QtWidgets.QAction(MainWindow)
        self.mRemoveBackgroundSequence.setObjectName("mRemoveBackgroundSequence")
        self.mProcessImageSequence = QtWidgets.QAction(MainWindow)
        self.mProcessImageSequence.setObjectName("mProcessImageSequence")
        self.mProcessBackgroundSequence = QtWidgets.QAction(MainWindow)
        self.mProcessBackgroundSequence.setObjectName("mProcessBackgroundSequence")
        self.mFIleAbortAcquisition = QtWidgets.QAction(MainWindow)
        self.mFIleAbortAcquisition.setObjectName("mFIleAbortAcquisition")
        self.mLoadBackgrounds = QtWidgets.QAction(MainWindow)
        self.mLoadBackgrounds.setObjectName("mLoadBackgrounds")
        self.mLoadReferences = QtWidgets.QAction(MainWindow)
        self.mLoadReferences.setObjectName("mLoadReferences")
        self.mFileMultipleExposures = QtWidgets.QAction(MainWindow)
        self.mFileMultipleExposures.setObjectName("mFileMultipleExposures")
        self.mFileDoHWPSweep = QtWidgets.QAction(MainWindow)
        self.mFileDoHWPSweep.setCheckable(True)
        self.mFileDoHWPSweep.setObjectName("mFileDoHWPSweep")
        self.fExpTypeHSG_TimeDomain = QtWidgets.QAction(MainWindow)
        self.fExpTypeHSG_TimeDomain.setCheckable(True)
        self.fExpTypeHSG_TimeDomain.setObjectName("fExpTypeHSG_TimeDomain")
        self.mFileSweepTHz = QtWidgets.QAction(MainWindow)
        self.mFileSweepTHz.setObjectName("mFileSweepTHz")
        self.mFileTimeDelaySweep = QtWidgets.QAction(MainWindow)
        self.mFileTimeDelaySweep.setCheckable(True)
        self.mFileTimeDelaySweep.setObjectName("mFileTimeDelaySweep")
        self.mFileTimeDelayPolarimetry = QtWidgets.QAction(MainWindow)
        self.mFileTimeDelayPolarimetry.setCheckable(True)
        self.mFileTimeDelayPolarimetry.setObjectName("mFileTimeDelayPolarimetry")
        self.menuSweeps.addAction(self.mFileDoHWPSweep)
        self.menuSweeps.addAction(self.mFileTimeDelaySweep)
        self.menuSweeps.addAction(self.mFileTimeDelayPolarimetry)
        self.menuSweeps.addAction(self.mFileScanNeLines)
        self.menuSweeps.addAction(self.mFileSweepTHz)
        self.menuSweeps.addAction(self.mFileDoSpecSweep)
        self.menuOther_Settings.addAction(self.mFileDoCRR)
        self.menuOther_Settings.addAction(self.mFileBreakTemp)
        self.menuOther_Settings.addAction(self.mFileTakeContinuous)
        self.menuOther_Settings.addAction(self.mFileEnableAll)
        self.menuOther_Settings.addAction(self.mFileMultipleExposures)
        self.menuOther_Settings.addAction(self.menuSweeps.menuAction())
        self.menuOther_Settings.addAction(self.mFIleAbortAcquisition)
        self.menuOther_Settings.addSeparator()
        self.menuOther_Settings.addAction(self.mFileFastExit)
        self.menuOther_Settings.addAction(self.mFileOpenDebugConsole)
        self.menuLive_Series.addAction(self.mRemoveImageSequence)
        self.menuLive_Series.addAction(self.mRemoveBackgroundSequence)
        self.menuLive_Series.addSeparator()
        self.menuLive_Series.addAction(self.mLoadBackgrounds)
        self.menuLive_Series.addAction(self.mLoadReferences)
        self.menuHSG_FVB.addAction(self.fExpTypeHSG_FVB)
        self.menuHSG_FVB.addAction(self.fExpTypeHSG_Image)
        self.menuHSG_FVB.addAction(self.fExpTypeHSG_PhotonCounting)
        self.menuHSG_FVB.addAction(self.fExpTypeHSG_TimeDomain)
        self.menuExperiment_Type.addAction(self.menuHSG_FVB.menuAction())
        self.menuExperiment_Type.addAction(self.fExpTypePL)
        self.menuExperiment_Type.addAction(self.fExpTypeAbs)
        self.menuExperiment_Type.addAction(self.fExpTypeTwo_Color_Abs)
        self.menuExperiment_Type.addAction(self.fExpTypeAlignment)
        self.menuLive_Plots.addAction(self.mLivePlotsDisableHistogramAutoscale)
        self.menuLive_Plots.addAction(self.mLivePlotsDisableRawPlots)
        self.menuLive_Plots.addAction(self.mLivePlotsForceAutoscale)
        self.menubar.addAction(self.menuOther_Settings.menuAction())
        self.menubar.addAction(self.menuLive_Series.menuAction())
        self.menubar.addAction(self.menuExperiment_Type.menuAction())
        self.menubar.addAction(self.menuLive_Plots.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.cSettingsReadMode.setCurrentIndex(4)
        self.cSettingsAcquisitionMode.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.cSettingsADChannel, self.cSettingsVSS)
        MainWindow.setTabOrder(self.cSettingsVSS, self.cSettingsReadMode)
        MainWindow.setTabOrder(self.cSettingsReadMode, self.cSettingsHSS)
        MainWindow.setTabOrder(self.cSettingsHSS, self.cSettingsTrigger)
        MainWindow.setTabOrder(self.cSettingsTrigger, self.cSettingsAcquisitionMode)
        MainWindow.setTabOrder(self.cSettingsAcquisitionMode, self.tHBin)
        MainWindow.setTabOrder(self.tHBin, self.tHStart)
        MainWindow.setTabOrder(self.tHStart, self.tHEnd)
        MainWindow.setTabOrder(self.tHEnd, self.tVBin)
        MainWindow.setTabOrder(self.tVBin, self.tVStart)
        MainWindow.setTabOrder(self.tVStart, self.tVEnd)
        MainWindow.setTabOrder(self.tVEnd, self.bSettingsApply)
        MainWindow.setTabOrder(self.bSettingsApply, self.bSettingsCancel)
        MainWindow.setTabOrder(self.bSettingsCancel, self.tBackgroundName)
        MainWindow.setTabOrder(self.tBackgroundName, self.tImageName)
        MainWindow.setTabOrder(self.tImageName, self.tSettingsDirectory)
        MainWindow.setTabOrder(self.tSettingsDirectory, self.bSettingsDirectory)
        MainWindow.setTabOrder(self.bSettingsDirectory, self.tSettingsCurrTemp)
        MainWindow.setTabOrder(self.tSettingsCurrTemp, self.tSettingsGotoTemp)
        MainWindow.setTabOrder(self.tSettingsGotoTemp, self.bSetTemp)
        MainWindow.setTabOrder(self.bSetTemp, self.tSettingsTempResponse)
        MainWindow.setTabOrder(self.tSettingsTempResponse, self.sbSpecWavelength)
        MainWindow.setTabOrder(self.sbSpecWavelength, self.bSpecSetWl)
        MainWindow.setTabOrder(self.bSpecSetWl, self.sbSpecGrating)
        MainWindow.setTabOrder(self.sbSpecGrating, self.cSettingsShutterEx)
        MainWindow.setTabOrder(self.cSettingsShutterEx, self.cSettingsShutter)
        MainWindow.setTabOrder(self.cSettingsShutter, self.bSpecSetGr)
        MainWindow.setTabOrder(self.bSpecSetGr, self.tSpecCurWl)
        MainWindow.setTabOrder(self.tSpecCurWl, self.cSpecGPIB)
        MainWindow.setTabOrder(self.cSpecGPIB, self.tSpecCurGr)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EMCCD"))
        self.gbSettings.setTitle(_translate("MainWindow", "CCD Settings"))
        self.groupBox_6.setTitle(_translate("MainWindow", "AD Channel"))
        self.groupBox_13.setTitle(_translate("MainWindow", "Horizontal Speed"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Vertical Speed"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Read Mode"))
        self.cSettingsReadMode.setItemText(0, _translate("MainWindow", "Full Vertical Binning"))
        self.cSettingsReadMode.setItemText(1, _translate("MainWindow", "Multi-Track"))
        self.cSettingsReadMode.setItemText(2, _translate("MainWindow", "Random-Track"))
        self.cSettingsReadMode.setItemText(3, _translate("MainWindow", "Single-Track"))
        self.cSettingsReadMode.setItemText(4, _translate("MainWindow", "Image"))
        self.groupBox_14.setTitle(_translate("MainWindow", "Trigger Type"))
        self.cSettingsTrigger.setItemText(0, _translate("MainWindow", "Internal"))
        self.cSettingsTrigger.setItemText(1, _translate("MainWindow", "External"))
        self.groupBox_15.setTitle(_translate("MainWindow", "Acquisition Mode"))
        self.cSettingsAcquisitionMode.setItemText(0, _translate("MainWindow", "NA"))
        self.cSettingsAcquisitionMode.setItemText(1, _translate("MainWindow", "Single Scan"))
        self.cSettingsAcquisitionMode.setItemText(2, _translate("MainWindow", "Accumulate"))
        self.cSettingsAcquisitionMode.setItemText(3, _translate("MainWindow", "Kinetic"))
        self.cSettingsAcquisitionMode.setItemText(4, _translate("MainWindow", "Fast Kinetics"))
        self.cSettingsAcquisitionMode.setItemText(5, _translate("MainWindow", "Run till abort"))
        self.cSettingsAcquisitionMode.setItemText(6, _translate("MainWindow", "NA"))
        self.cSettingsAcquisitionMode.setItemText(7, _translate("MainWindow", "NA"))
        self.cSettingsAcquisitionMode.setItemText(8, _translate("MainWindow", "NA"))
        self.cSettingsAcquisitionMode.setItemText(9, _translate("MainWindow", "Time delayed integration"))
        self.groupBox_50.setTitle(_translate("MainWindow", "External Shutter"))
        self.cSettingsShutterEx.setItemText(0, _translate("MainWindow", "Fully Auto"))
        self.cSettingsShutterEx.setItemText(1, _translate("MainWindow", "Permanently Open"))
        self.cSettingsShutterEx.setItemText(2, _translate("MainWindow", "Permanently Closed"))
        self.groupBox_51.setTitle(_translate("MainWindow", "Internal Shutter"))
        self.cSettingsShutter.setItemText(0, _translate("MainWindow", "Fully Auto"))
        self.cSettingsShutter.setItemText(1, _translate("MainWindow", "Permanently Open"))
        self.cSettingsShutter.setItemText(2, _translate("MainWindow", "Permanently Closed"))
        self.gbImageParams.setTitle(_translate("MainWindow", "Image Parameters"))
        self.groupBox_18.setTitle(_translate("MainWindow", "Horizontal Start"))
        self.groupBox_17.setTitle(_translate("MainWindow", "Vertical Binning"))
        self.groupBox_16.setTitle(_translate("MainWindow", "Horizontal Binning"))
        self.groupBox_19.setTitle(_translate("MainWindow", "Horizontal End"))
        self.groupBox_20.setTitle(_translate("MainWindow", "Vertical Start"))
        self.groupBox_21.setTitle(_translate("MainWindow", "Vertical End"))
        self.bSettingsApply.setText(_translate("MainWindow", "Apply"))
        self.bSettingsCancel.setText(_translate("MainWindow", "Cancel"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Save settings"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Background Name"))
        self.tBackgroundName.setText(_translate("MainWindow", "bg_{VBIN}bin_{VST}st_{VEN}en_{EXP}s_{GAIN}g_4x_"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Image Name"))
        self.tImageName.setText(_translate("MainWindow", "test"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Save Directory"))
        self.bSettingsDirectory.setText(_translate("MainWindow", "Choose.."))
        self.groupBox_3.setTitle(_translate("MainWindow", "Temperature Control"))
        self.groupBox_22.setTitle(_translate("MainWindow", "Current Temp"))
        self.tSettingsCurrTemp.setText(_translate("MainWindow", "20"))
        self.groupBox_23.setTitle(_translate("MainWindow", "Desired Temp"))
        self.bSetTemp.setText(_translate("MainWindow", "Set Temperature"))
        self.groupBox_24.setTitle(_translate("MainWindow", "Response"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSettings), _translate("MainWindow", "Settings"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Start (nm)"))
        self.bSpecSetGr.setText(_translate("MainWindow", "Set"))
        self.groupBox.setTitle(_translate("MainWindow", "Grating"))
        self.groupBox_47.setTitle(_translate("MainWindow", "Current Wavelength"))
        self.bSpecSetWl.setText(_translate("MainWindow", "Set"))
        self.groupBox_49.setTitle(_translate("MainWindow", "GPIB"))
        self.cSpecGPIB.setToolTip(_translate("MainWindow", "ASRL1"))
        self.groupBox_33.setTitle(_translate("MainWindow", "Center wavelength"))
        self.groupBox_48.setTitle(_translate("MainWindow", "Current Grating"))
        self.groupBox_4.setTitle(_translate("MainWindow", "End (nm)"))
        self.gbSpecStartSB.setTitle(_translate("MainWindow", "Start (SB)"))
        self.gbSpecEndSB.setTitle(_translate("MainWindow", "End (SB)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSpec), _translate("MainWindow", "Spectrometer"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Misc Tools"))
        self.menuOther_Settings.setTitle(_translate("MainWindow", "Other Settings"))
        self.menuSweeps.setTitle(_translate("MainWindow", "Sweeps"))
        self.menuLive_Series.setTitle(_translate("MainWindow", "Sequence Controls"))
        self.menuExperiment_Type.setTitle(_translate("MainWindow", "Experiment Type"))
        self.menuHSG_FVB.setTitle(_translate("MainWindow", "HSG"))
        self.menuLive_Plots.setTitle(_translate("MainWindow", "Live Plots"))
        self.mFileDoCRR.setText(_translate("MainWindow", "Do cosmic ray removal"))
        self.mFileBreakTemp.setText(_translate("MainWindow", "Break temperature loop"))
        self.mFileTakeContinuous.setText(_translate("MainWindow", "Take continuous"))
        self.actionValue.setText(_translate("MainWindow", "value"))
        self.mFileEnableAll.setText(_translate("MainWindow", "Enable Extra Settings"))
        self.mFileSumSpectraUndo.setText(_translate("MainWindow", "Undo Last"))
        self.mSeriesSum.setText(_translate("MainWindow", "Do Series"))
        self.mSeriesUndo.setText(_translate("MainWindow", "Undo Last"))
        self.fExpTypeHSGImage.setText(_translate("MainWindow", "HSG Image"))
        self.fExpTypePL.setText(_translate("MainWindow", "PL"))
        self.fExpTypeAbs.setText(_translate("MainWindow", "Abs"))
        self.mFileFastExit.setText(_translate("MainWindow", "Exit without shutdown"))
        self.fExpTypeTwo_Color_Abs.setText(_translate("MainWindow", "Two Color Abs"))
        self.mLivePlotsDisableHistogramAutoscale.setText(_translate("MainWindow", "Disable Histogram autoscale"))
        self.mLivePlotsDisableRawPlots.setText(_translate("MainWindow", "Disable Raw Plots"))
        self.mRemoveImageSequence.setText(_translate("MainWindow", "Remove Image Sequence"))
        self.m.setText(_translate("MainWindow", "Set Current as First"))
        self.m.setToolTip(_translate("MainWindow", "Set the current image as the first image in the series"))
        self.fExpTypeAlignment.setText(_translate("MainWindow", "Alignment"))
        self.mLivePlotsForceAutoscale.setText(_translate("MainWindow", "Force Histogram Autoscale"))
        self.fExpTypeHSG_FVB.setText(_translate("MainWindow", "FVB"))
        self.fExpTypeHSG_Image.setText(_translate("MainWindow", "Image"))
        self.fExpTypeHSG_PhotonCounting.setText(_translate("MainWindow", "Photon Counting"))
        self.mFileDoSpecSweep.setText(_translate("MainWindow", "Do Spec Sweep"))
        self.mFileScanNeLines.setText(_translate("MainWindow", "Scan Ne Lines"))
        self.mFileOpenDebugConsole.setText(_translate("MainWindow", "Open Debug Console"))
        self.mRemoveBackgroundSequence.setText(_translate("MainWindow", "Remove Background Sequence"))
        self.mProcessImageSequence.setText(_translate("MainWindow", "Process Image Sequence"))
        self.mProcessBackgroundSequence.setText(_translate("MainWindow", "Process Background Sequence"))
        self.mFIleAbortAcquisition.setText(_translate("MainWindow", "Abort Acquisition"))
        self.mLoadBackgrounds.setText(_translate("MainWindow", "Load Background"))
        self.mLoadReferences.setText(_translate("MainWindow", "Load Reference"))
        self.mFileMultipleExposures.setText(_translate("MainWindow", "Multiple Exposures"))
        self.mFileDoHWPSweep.setText(_translate("MainWindow", "Do HWP Sweep"))
        self.fExpTypeHSG_TimeDomain.setText(_translate("MainWindow", "Time Domain"))
        self.mFileSweepTHz.setText(_translate("MainWindow", "Sweep THz Power"))
        self.mFileTimeDelaySweep.setText(_translate("MainWindow", "Time Delay Sweep"))
        self.mFileTimeDelayPolarimetry.setText(_translate("MainWindow", "Time Delayed Polarimetry"))

from InstsAndQt.cQt.MCLineEdit import MCLineEdit
from InstsAndQt.customQt import QINumberEdit
from InstsAndQt.instrumentgpib import InstrumentGPIB
from .resources_rc import *
