# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\dvalovcin\Documents\GitHub\EMCCD-psychic\UIs\mainWindow.ui'
#
# Created: Fri Jun 19 13:28:08 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(827, 735)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/test/icon.jpg")), QtGui.QIcon.Selected, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolTip(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideRight)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabSettings = QtGui.QWidget()
        self.tabSettings.setObjectName(_fromUtf8("tabSettings"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tabSettings)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.gbSettings = QtGui.QGroupBox(self.tabSettings)
        self.gbSettings.setObjectName(_fromUtf8("gbSettings"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.gbSettings)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox_6 = QtGui.QGroupBox(self.gbSettings)
        self.groupBox_6.setFlat(True)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_4.setContentsMargins(0, 10, 0, 0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.cSettingsADChannel = QtGui.QComboBox(self.groupBox_6)
        self.cSettingsADChannel.setObjectName(_fromUtf8("cSettingsADChannel"))
        self.verticalLayout_4.addWidget(self.cSettingsADChannel)
        self.gridLayout_2.addWidget(self.groupBox_6, 0, 0, 1, 1)
        self.groupBox_13 = QtGui.QGroupBox(self.gbSettings)
        self.groupBox_13.setFlat(True)
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.groupBox_13)
        self.horizontalLayout_11.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.cSettingsHSS = QtGui.QComboBox(self.groupBox_13)
        self.cSettingsHSS.setObjectName(_fromUtf8("cSettingsHSS"))
        self.horizontalLayout_11.addWidget(self.cSettingsHSS)
        self.gridLayout_2.addWidget(self.groupBox_13, 2, 1, 1, 1)
        self.groupBox_11 = QtGui.QGroupBox(self.gbSettings)
        self.groupBox_11.setFlat(True)
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.groupBox_11)
        self.horizontalLayout_9.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.cSettingsVSS = QtGui.QComboBox(self.groupBox_11)
        self.cSettingsVSS.setObjectName(_fromUtf8("cSettingsVSS"))
        self.horizontalLayout_9.addWidget(self.cSettingsVSS)
        self.gridLayout_2.addWidget(self.groupBox_11, 0, 1, 1, 1)
        self.groupBox_12 = QtGui.QGroupBox(self.gbSettings)
        self.groupBox_12.setFlat(True)
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.groupBox_12)
        self.horizontalLayout_10.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.cSettingsReadMode = QtGui.QComboBox(self.groupBox_12)
        self.cSettingsReadMode.setEnabled(False)
        self.cSettingsReadMode.setObjectName(_fromUtf8("cSettingsReadMode"))
        self.cSettingsReadMode.addItem(_fromUtf8(""))
        self.cSettingsReadMode.addItem(_fromUtf8(""))
        self.cSettingsReadMode.addItem(_fromUtf8(""))
        self.cSettingsReadMode.addItem(_fromUtf8(""))
        self.cSettingsReadMode.addItem(_fromUtf8(""))
        self.horizontalLayout_10.addWidget(self.cSettingsReadMode)
        self.gridLayout_2.addWidget(self.groupBox_12, 2, 0, 1, 1)
        self.groupBox_14 = QtGui.QGroupBox(self.gbSettings)
        self.groupBox_14.setFlat(True)
        self.groupBox_14.setObjectName(_fromUtf8("groupBox_14"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.groupBox_14)
        self.horizontalLayout_12.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.cSettingsTrigger = QtGui.QComboBox(self.groupBox_14)
        self.cSettingsTrigger.setObjectName(_fromUtf8("cSettingsTrigger"))
        self.cSettingsTrigger.addItem(_fromUtf8(""))
        self.cSettingsTrigger.addItem(_fromUtf8(""))
        self.horizontalLayout_12.addWidget(self.cSettingsTrigger)
        self.gridLayout_2.addWidget(self.groupBox_14, 3, 0, 1, 1)
        self.groupBox_15 = QtGui.QGroupBox(self.gbSettings)
        self.groupBox_15.setFlat(True)
        self.groupBox_15.setObjectName(_fromUtf8("groupBox_15"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.groupBox_15)
        self.horizontalLayout_13.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.cSettingsAcquisitionMode = QtGui.QComboBox(self.groupBox_15)
        self.cSettingsAcquisitionMode.setEnabled(False)
        self.cSettingsAcquisitionMode.setObjectName(_fromUtf8("cSettingsAcquisitionMode"))
        self.cSettingsAcquisitionMode.addItem(_fromUtf8(""))
        self.cSettingsAcquisitionMode.addItem(_fromUtf8(""))
        self.cSettingsAcquisitionMode.addItem(_fromUtf8(""))
        self.cSettingsAcquisitionMode.addItem(_fromUtf8(""))
        self.cSettingsAcquisitionMode.addItem(_fromUtf8(""))
        self.cSettingsAcquisitionMode.addItem(_fromUtf8(""))
        self.cSettingsAcquisitionMode.addItem(_fromUtf8(""))
        self.cSettingsAcquisitionMode.addItem(_fromUtf8(""))
        self.cSettingsAcquisitionMode.addItem(_fromUtf8(""))
        self.cSettingsAcquisitionMode.addItem(_fromUtf8(""))
        self.horizontalLayout_13.addWidget(self.cSettingsAcquisitionMode)
        self.gridLayout_2.addWidget(self.groupBox_15, 3, 1, 1, 1)
        self.groupBox_50 = QtGui.QGroupBox(self.gbSettings)
        self.groupBox_50.setFlat(True)
        self.groupBox_50.setObjectName(_fromUtf8("groupBox_50"))
        self.horizontalLayout_42 = QtGui.QHBoxLayout(self.groupBox_50)
        self.horizontalLayout_42.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_42.setObjectName(_fromUtf8("horizontalLayout_42"))
        self.cSettingsShutterEx = QtGui.QComboBox(self.groupBox_50)
        self.cSettingsShutterEx.setObjectName(_fromUtf8("cSettingsShutterEx"))
        self.cSettingsShutterEx.addItem(_fromUtf8(""))
        self.cSettingsShutterEx.addItem(_fromUtf8(""))
        self.cSettingsShutterEx.addItem(_fromUtf8(""))
        self.horizontalLayout_42.addWidget(self.cSettingsShutterEx)
        self.gridLayout_2.addWidget(self.groupBox_50, 4, 1, 1, 1)
        self.groupBox_51 = QtGui.QGroupBox(self.gbSettings)
        self.groupBox_51.setFlat(True)
        self.groupBox_51.setObjectName(_fromUtf8("groupBox_51"))
        self.horizontalLayout_43 = QtGui.QHBoxLayout(self.groupBox_51)
        self.horizontalLayout_43.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_43.setObjectName(_fromUtf8("horizontalLayout_43"))
        self.cSettingsShutter = QtGui.QComboBox(self.groupBox_51)
        self.cSettingsShutter.setEnabled(False)
        self.cSettingsShutter.setObjectName(_fromUtf8("cSettingsShutter"))
        self.cSettingsShutter.addItem(_fromUtf8(""))
        self.cSettingsShutter.addItem(_fromUtf8(""))
        self.cSettingsShutter.addItem(_fromUtf8(""))
        self.horizontalLayout_43.addWidget(self.cSettingsShutter)
        self.gridLayout_2.addWidget(self.groupBox_51, 4, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        self.gbImageParams = QtGui.QGroupBox(self.gbSettings)
        self.gbImageParams.setEnabled(True)
        self.gbImageParams.setObjectName(_fromUtf8("gbImageParams"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.gbImageParams)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.groupBox_18 = QtGui.QGroupBox(self.gbImageParams)
        self.groupBox_18.setFlat(True)
        self.groupBox_18.setObjectName(_fromUtf8("groupBox_18"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.groupBox_18)
        self.horizontalLayout_16.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.tHStart = QINumberEdit(self.groupBox_18)
        self.tHStart.setEnabled(False)
        self.tHStart.setObjectName(_fromUtf8("tHStart"))
        self.horizontalLayout_16.addWidget(self.tHStart)
        self.gridLayout_4.addWidget(self.groupBox_18, 0, 1, 1, 1)
        self.groupBox_17 = QtGui.QGroupBox(self.gbImageParams)
        self.groupBox_17.setFlat(True)
        self.groupBox_17.setObjectName(_fromUtf8("groupBox_17"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.groupBox_17)
        self.horizontalLayout_15.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.tVBin = QINumberEdit(self.groupBox_17)
        self.tVBin.setEnabled(False)
        self.tVBin.setObjectName(_fromUtf8("tVBin"))
        self.horizontalLayout_15.addWidget(self.tVBin)
        self.gridLayout_4.addWidget(self.groupBox_17, 2, 0, 1, 1)
        self.groupBox_16 = QtGui.QGroupBox(self.gbImageParams)
        self.groupBox_16.setFlat(True)
        self.groupBox_16.setObjectName(_fromUtf8("groupBox_16"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.groupBox_16)
        self.horizontalLayout_14.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.tHBin = QINumberEdit(self.groupBox_16)
        self.tHBin.setEnabled(False)
        self.tHBin.setObjectName(_fromUtf8("tHBin"))
        self.horizontalLayout_14.addWidget(self.tHBin)
        self.gridLayout_4.addWidget(self.groupBox_16, 0, 0, 1, 1)
        self.groupBox_19 = QtGui.QGroupBox(self.gbImageParams)
        self.groupBox_19.setFlat(True)
        self.groupBox_19.setObjectName(_fromUtf8("groupBox_19"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.groupBox_19)
        self.horizontalLayout_17.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.tHEnd = QINumberEdit(self.groupBox_19)
        self.tHEnd.setEnabled(False)
        self.tHEnd.setObjectName(_fromUtf8("tHEnd"))
        self.horizontalLayout_17.addWidget(self.tHEnd)
        self.gridLayout_4.addWidget(self.groupBox_19, 0, 2, 1, 1)
        self.groupBox_20 = QtGui.QGroupBox(self.gbImageParams)
        self.groupBox_20.setFlat(True)
        self.groupBox_20.setObjectName(_fromUtf8("groupBox_20"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout(self.groupBox_20)
        self.horizontalLayout_18.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.tVStart = QINumberEdit(self.groupBox_20)
        self.tVStart.setObjectName(_fromUtf8("tVStart"))
        self.horizontalLayout_18.addWidget(self.tVStart)
        self.gridLayout_4.addWidget(self.groupBox_20, 2, 1, 1, 1)
        self.groupBox_21 = QtGui.QGroupBox(self.gbImageParams)
        self.groupBox_21.setFlat(True)
        self.groupBox_21.setObjectName(_fromUtf8("groupBox_21"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout(self.groupBox_21)
        self.horizontalLayout_19.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.tVEnd = QINumberEdit(self.groupBox_21)
        self.tVEnd.setObjectName(_fromUtf8("tVEnd"))
        self.horizontalLayout_19.addWidget(self.tVEnd)
        self.gridLayout_4.addWidget(self.groupBox_21, 2, 2, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_4)
        self.verticalLayout_5.addWidget(self.gbImageParams)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.bSettingsApply = QtGui.QPushButton(self.gbSettings)
        self.bSettingsApply.setObjectName(_fromUtf8("bSettingsApply"))
        self.horizontalLayout_3.addWidget(self.bSettingsApply)
        self.bSettingsCancel = QtGui.QPushButton(self.gbSettings)
        self.bSettingsCancel.setObjectName(_fromUtf8("bSettingsCancel"))
        self.horizontalLayout_3.addWidget(self.bSettingsCancel)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_7.addWidget(self.gbSettings)
        self.groupBox_5 = QtGui.QGroupBox(self.tabSettings)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_8.setFlat(True)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_8.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.tBackgroundName = QtGui.QLineEdit(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tBackgroundName.sizePolicy().hasHeightForWidth())
        self.tBackgroundName.setSizePolicy(sizePolicy)
        self.tBackgroundName.setObjectName(_fromUtf8("tBackgroundName"))
        self.horizontalLayout_8.addWidget(self.tBackgroundName)
        self.horizontalLayout_7.addWidget(self.groupBox_8)
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_7.setFlat(True)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_6.setContentsMargins(0, 10, 0, 0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.tImageName = QtGui.QLineEdit(self.groupBox_7)
        self.tImageName.setObjectName(_fromUtf8("tImageName"))
        self.verticalLayout_6.addWidget(self.tImageName)
        self.horizontalLayout_7.addWidget(self.groupBox_7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.groupBox_9 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_9.setFlat(True)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_5.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.tSettingsDirectory = QtGui.QLineEdit(self.groupBox_9)
        self.tSettingsDirectory.setObjectName(_fromUtf8("tSettingsDirectory"))
        self.horizontalLayout_5.addWidget(self.tSettingsDirectory)
        self.bSettingsDirectory = QtGui.QPushButton(self.groupBox_9)
        self.bSettingsDirectory.setObjectName(_fromUtf8("bSettingsDirectory"))
        self.horizontalLayout_5.addWidget(self.bSettingsDirectory)
        self.verticalLayout_3.addWidget(self.groupBox_9)
        self.verticalLayout_7.addWidget(self.groupBox_5)
        self.groupBox_3 = QtGui.QGroupBox(self.tabSettings)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.groupBox_22 = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox_22.setFlat(True)
        self.groupBox_22.setObjectName(_fromUtf8("groupBox_22"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout(self.groupBox_22)
        self.horizontalLayout_20.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.tSettingsCurrTemp = QtGui.QLineEdit(self.groupBox_22)
        self.tSettingsCurrTemp.setReadOnly(True)
        self.tSettingsCurrTemp.setObjectName(_fromUtf8("tSettingsCurrTemp"))
        self.horizontalLayout_20.addWidget(self.tSettingsCurrTemp)
        self.horizontalLayout_4.addWidget(self.groupBox_22)
        self.groupBox_23 = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox_23.setFlat(True)
        self.groupBox_23.setObjectName(_fromUtf8("groupBox_23"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout(self.groupBox_23)
        self.horizontalLayout_21.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.tSettingsGotoTemp = QINumberEdit(self.groupBox_23)
        self.tSettingsGotoTemp.setObjectName(_fromUtf8("tSettingsGotoTemp"))
        self.horizontalLayout_21.addWidget(self.tSettingsGotoTemp)
        self.horizontalLayout_4.addWidget(self.groupBox_23)
        self.bSetTemp = QtGui.QPushButton(self.groupBox_3)
        self.bSetTemp.setObjectName(_fromUtf8("bSetTemp"))
        self.horizontalLayout_4.addWidget(self.bSetTemp)
        self.groupBox_24 = QtGui.QGroupBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_24.sizePolicy().hasHeightForWidth())
        self.groupBox_24.setSizePolicy(sizePolicy)
        self.groupBox_24.setFlat(True)
        self.groupBox_24.setObjectName(_fromUtf8("groupBox_24"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout(self.groupBox_24)
        self.horizontalLayout_22.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.tSettingsTempResponse = QtGui.QLineEdit(self.groupBox_24)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tSettingsTempResponse.sizePolicy().hasHeightForWidth())
        self.tSettingsTempResponse.setSizePolicy(sizePolicy)
        self.tSettingsTempResponse.setReadOnly(True)
        self.tSettingsTempResponse.setObjectName(_fromUtf8("tSettingsTempResponse"))
        self.horizontalLayout_22.addWidget(self.tSettingsTempResponse)
        self.horizontalLayout_4.addWidget(self.groupBox_24)
        self.verticalLayout_7.addWidget(self.groupBox_3)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.tabWidget.addTab(self.tabSettings, _fromUtf8(""))
        self.tabSpec = QtGui.QWidget()
        self.tabSpec.setObjectName(_fromUtf8("tabSpec"))
        self.horizontalLayout_40 = QtGui.QHBoxLayout(self.tabSpec)
        self.horizontalLayout_40.setObjectName(_fromUtf8("horizontalLayout_40"))
        self.gridLayout_16 = QtGui.QGridLayout()
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.bSpecSetGr = QtGui.QPushButton(self.tabSpec)
        self.bSpecSetGr.setObjectName(_fromUtf8("bSpecSetGr"))
        self.gridLayout_16.addWidget(self.bSpecSetGr, 2, 1, 1, 1)
        self.bSpecSetWl = QtGui.QPushButton(self.tabSpec)
        self.bSpecSetWl.setObjectName(_fromUtf8("bSpecSetWl"))
        self.gridLayout_16.addWidget(self.bSpecSetWl, 0, 1, 1, 1)
        self.groupBox_33 = QtGui.QGroupBox(self.tabSpec)
        self.groupBox_33.setFlat(True)
        self.groupBox_33.setObjectName(_fromUtf8("groupBox_33"))
        self.horizontalLayout_31 = QtGui.QHBoxLayout(self.groupBox_33)
        self.horizontalLayout_31.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.sbSpecWavelength = QtGui.QDoubleSpinBox(self.groupBox_33)
        self.sbSpecWavelength.setSpecialValueText(_fromUtf8(""))
        self.sbSpecWavelength.setMaximum(1200.0)
        self.sbSpecWavelength.setObjectName(_fromUtf8("sbSpecWavelength"))
        self.horizontalLayout_31.addWidget(self.sbSpecWavelength)
        self.gridLayout_16.addWidget(self.groupBox_33, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.tabSpec)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_36 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_36.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_36.setObjectName(_fromUtf8("horizontalLayout_36"))
        self.sbSpecGrating = QtGui.QSpinBox(self.groupBox)
        self.sbSpecGrating.setMinimum(1)
        self.sbSpecGrating.setMaximum(2)
        self.sbSpecGrating.setObjectName(_fromUtf8("sbSpecGrating"))
        self.horizontalLayout_36.addWidget(self.sbSpecGrating)
        self.gridLayout_16.addWidget(self.groupBox, 2, 0, 1, 1)
        self.groupBox_47 = QtGui.QGroupBox(self.tabSpec)
        self.groupBox_47.setFlat(True)
        self.groupBox_47.setObjectName(_fromUtf8("groupBox_47"))
        self.horizontalLayout_38 = QtGui.QHBoxLayout(self.groupBox_47)
        self.horizontalLayout_38.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_38.setObjectName(_fromUtf8("horizontalLayout_38"))
        self.tSpecCurWl = QtGui.QLineEdit(self.groupBox_47)
        self.tSpecCurWl.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tSpecCurWl.sizePolicy().hasHeightForWidth())
        self.tSpecCurWl.setSizePolicy(sizePolicy)
        self.tSpecCurWl.setObjectName(_fromUtf8("tSpecCurWl"))
        self.horizontalLayout_38.addWidget(self.tSpecCurWl)
        self.gridLayout_16.addWidget(self.groupBox_47, 0, 2, 1, 1)
        self.groupBox_49 = QtGui.QGroupBox(self.tabSpec)
        self.groupBox_49.setFlat(True)
        self.groupBox_49.setObjectName(_fromUtf8("groupBox_49"))
        self.horizontalLayout_41 = QtGui.QHBoxLayout(self.groupBox_49)
        self.horizontalLayout_41.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_41.setObjectName(_fromUtf8("horizontalLayout_41"))
        self.cSpecGPIB = QtGui.QComboBox(self.groupBox_49)
        self.cSpecGPIB.setObjectName(_fromUtf8("cSpecGPIB"))
        self.horizontalLayout_41.addWidget(self.cSpecGPIB)
        self.gridLayout_16.addWidget(self.groupBox_49, 3, 0, 1, 1)
        self.groupBox_48 = QtGui.QGroupBox(self.tabSpec)
        self.groupBox_48.setFlat(True)
        self.groupBox_48.setObjectName(_fromUtf8("groupBox_48"))
        self.horizontalLayout_39 = QtGui.QHBoxLayout(self.groupBox_48)
        self.horizontalLayout_39.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_39.setObjectName(_fromUtf8("horizontalLayout_39"))
        self.tSpecCurGr = QtGui.QLineEdit(self.groupBox_48)
        self.tSpecCurGr.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tSpecCurGr.sizePolicy().hasHeightForWidth())
        self.tSpecCurGr.setSizePolicy(sizePolicy)
        self.tSpecCurGr.setObjectName(_fromUtf8("tSpecCurGr"))
        self.horizontalLayout_39.addWidget(self.tSpecCurGr)
        self.gridLayout_16.addWidget(self.groupBox_48, 2, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem2, 0, 3, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem3, 4, 0, 1, 1)
        self.horizontalLayout_40.addLayout(self.gridLayout_16)
        self.tabWidget.addTab(self.tabSpec, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 827, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuOther_Settings = QtGui.QMenu(self.menubar)
        self.menuOther_Settings.setObjectName(_fromUtf8("menuOther_Settings"))
        self.menuLive_Series = QtGui.QMenu(self.menubar)
        self.menuLive_Series.setObjectName(_fromUtf8("menuLive_Series"))
        self.menuExperiment_Type = QtGui.QMenu(self.menubar)
        self.menuExperiment_Type.setObjectName(_fromUtf8("menuExperiment_Type"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.mFileDoCRR = QtGui.QAction(MainWindow)
        self.mFileDoCRR.setCheckable(True)
        self.mFileDoCRR.setChecked(True)
        self.mFileDoCRR.setObjectName(_fromUtf8("mFileDoCRR"))
        self.mFileBreakTemp = QtGui.QAction(MainWindow)
        self.mFileBreakTemp.setEnabled(False)
        self.mFileBreakTemp.setObjectName(_fromUtf8("mFileBreakTemp"))
        self.mFileTakeContinuous = QtGui.QAction(MainWindow)
        self.mFileTakeContinuous.setCheckable(True)
        self.mFileTakeContinuous.setObjectName(_fromUtf8("mFileTakeContinuous"))
        self.actionValue = QtGui.QAction(MainWindow)
        self.actionValue.setObjectName(_fromUtf8("actionValue"))
        self.mFileEnableAll = QtGui.QAction(MainWindow)
        self.mFileEnableAll.setCheckable(True)
        self.mFileEnableAll.setObjectName(_fromUtf8("mFileEnableAll"))
        self.mFileSumSpectraUndo = QtGui.QAction(MainWindow)
        self.mFileSumSpectraUndo.setObjectName(_fromUtf8("mFileSumSpectraUndo"))
        self.mSeriesSum = QtGui.QAction(MainWindow)
        self.mSeriesSum.setCheckable(True)
        self.mSeriesSum.setChecked(True)
        self.mSeriesSum.setObjectName(_fromUtf8("mSeriesSum"))
        self.mSeriesUndo = QtGui.QAction(MainWindow)
        self.mSeriesUndo.setEnabled(False)
        self.mSeriesUndo.setObjectName(_fromUtf8("mSeriesUndo"))
        self.fExpTypeHSG = QtGui.QAction(MainWindow)
        self.fExpTypeHSG.setCheckable(True)
        self.fExpTypeHSG.setChecked(True)
        self.fExpTypeHSG.setObjectName(_fromUtf8("fExpTypeHSG"))
        self.fExpTypePL = QtGui.QAction(MainWindow)
        self.fExpTypePL.setCheckable(True)
        self.fExpTypePL.setObjectName(_fromUtf8("fExpTypePL"))
        self.fExpTypeAbs = QtGui.QAction(MainWindow)
        self.fExpTypeAbs.setCheckable(True)
        self.fExpTypeAbs.setObjectName(_fromUtf8("fExpTypeAbs"))
        self.mFileFastExit = QtGui.QAction(MainWindow)
        self.mFileFastExit.setObjectName(_fromUtf8("mFileFastExit"))
        self.fExpTypeTwo_Color_Abs = QtGui.QAction(MainWindow)
        self.fExpTypeTwo_Color_Abs.setCheckable(True)
        self.fExpTypeTwo_Color_Abs.setObjectName(_fromUtf8("fExpTypeTwo_Color_Abs"))
        self.menuOther_Settings.addAction(self.mFileDoCRR)
        self.menuOther_Settings.addAction(self.mFileBreakTemp)
        self.menuOther_Settings.addAction(self.mFileTakeContinuous)
        self.menuOther_Settings.addAction(self.mFileEnableAll)
        self.menuOther_Settings.addSeparator()
        self.menuOther_Settings.addAction(self.mFileFastExit)
        self.menuLive_Series.addAction(self.mSeriesSum)
        self.menuLive_Series.addAction(self.mSeriesUndo)
        self.menuExperiment_Type.addAction(self.fExpTypeHSG)
        self.menuExperiment_Type.addAction(self.fExpTypePL)
        self.menuExperiment_Type.addAction(self.fExpTypeAbs)
        self.menuExperiment_Type.addAction(self.fExpTypeTwo_Color_Abs)
        self.menubar.addAction(self.menuOther_Settings.menuAction())
        self.menubar.addAction(self.menuLive_Series.menuAction())
        self.menubar.addAction(self.menuExperiment_Type.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.cSettingsReadMode.setCurrentIndex(4)
        self.cSettingsAcquisitionMode.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.cSettingsADChannel, self.cSettingsVSS)
        MainWindow.setTabOrder(self.cSettingsVSS, self.cSettingsReadMode)
        MainWindow.setTabOrder(self.cSettingsReadMode, self.cSettingsHSS)
        MainWindow.setTabOrder(self.cSettingsHSS, self.cSettingsTrigger)
        MainWindow.setTabOrder(self.cSettingsTrigger, self.cSettingsAcquisitionMode)
        MainWindow.setTabOrder(self.cSettingsAcquisitionMode, self.tHBin)
        MainWindow.setTabOrder(self.tHBin, self.tHStart)
        MainWindow.setTabOrder(self.tHStart, self.tHEnd)
        MainWindow.setTabOrder(self.tHEnd, self.tVBin)
        MainWindow.setTabOrder(self.tVBin, self.tVStart)
        MainWindow.setTabOrder(self.tVStart, self.tVEnd)
        MainWindow.setTabOrder(self.tVEnd, self.bSettingsApply)
        MainWindow.setTabOrder(self.bSettingsApply, self.bSettingsCancel)
        MainWindow.setTabOrder(self.bSettingsCancel, self.tBackgroundName)
        MainWindow.setTabOrder(self.tBackgroundName, self.tImageName)
        MainWindow.setTabOrder(self.tImageName, self.tSettingsDirectory)
        MainWindow.setTabOrder(self.tSettingsDirectory, self.bSettingsDirectory)
        MainWindow.setTabOrder(self.bSettingsDirectory, self.tSettingsCurrTemp)
        MainWindow.setTabOrder(self.tSettingsCurrTemp, self.tSettingsGotoTemp)
        MainWindow.setTabOrder(self.tSettingsGotoTemp, self.bSetTemp)
        MainWindow.setTabOrder(self.bSetTemp, self.tSettingsTempResponse)
        MainWindow.setTabOrder(self.tSettingsTempResponse, self.sbSpecWavelength)
        MainWindow.setTabOrder(self.sbSpecWavelength, self.bSpecSetWl)
        MainWindow.setTabOrder(self.bSpecSetWl, self.sbSpecGrating)
        MainWindow.setTabOrder(self.sbSpecGrating, self.cSettingsShutterEx)
        MainWindow.setTabOrder(self.cSettingsShutterEx, self.cSettingsShutter)
        MainWindow.setTabOrder(self.cSettingsShutter, self.bSpecSetGr)
        MainWindow.setTabOrder(self.bSpecSetGr, self.tSpecCurWl)
        MainWindow.setTabOrder(self.tSpecCurWl, self.cSpecGPIB)
        MainWindow.setTabOrder(self.cSpecGPIB, self.tSpecCurGr)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "EMCCD", None))
        self.gbSettings.setTitle(_translate("MainWindow", "CCD Settings", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "AD Channel", None))
        self.groupBox_13.setTitle(_translate("MainWindow", "Horizontal Speed", None))
        self.groupBox_11.setTitle(_translate("MainWindow", "Vertical Speed", None))
        self.groupBox_12.setTitle(_translate("MainWindow", "Read Mode", None))
        self.cSettingsReadMode.setItemText(0, _translate("MainWindow", "Full Vertical Binning", None))
        self.cSettingsReadMode.setItemText(1, _translate("MainWindow", "Multi-Track", None))
        self.cSettingsReadMode.setItemText(2, _translate("MainWindow", "Random-Track", None))
        self.cSettingsReadMode.setItemText(3, _translate("MainWindow", "Single-Track", None))
        self.cSettingsReadMode.setItemText(4, _translate("MainWindow", "Image", None))
        self.groupBox_14.setTitle(_translate("MainWindow", "Trigger Type", None))
        self.cSettingsTrigger.setItemText(0, _translate("MainWindow", "Internal", None))
        self.cSettingsTrigger.setItemText(1, _translate("MainWindow", "External", None))
        self.groupBox_15.setTitle(_translate("MainWindow", "Acquisition Mode", None))
        self.cSettingsAcquisitionMode.setItemText(0, _translate("MainWindow", "NA", None))
        self.cSettingsAcquisitionMode.setItemText(1, _translate("MainWindow", "Single Scan", None))
        self.cSettingsAcquisitionMode.setItemText(2, _translate("MainWindow", "Accumulate", None))
        self.cSettingsAcquisitionMode.setItemText(3, _translate("MainWindow", "Kinetic", None))
        self.cSettingsAcquisitionMode.setItemText(4, _translate("MainWindow", "Fast Kinetics", None))
        self.cSettingsAcquisitionMode.setItemText(5, _translate("MainWindow", "Run till abort", None))
        self.cSettingsAcquisitionMode.setItemText(6, _translate("MainWindow", "NA", None))
        self.cSettingsAcquisitionMode.setItemText(7, _translate("MainWindow", "NA", None))
        self.cSettingsAcquisitionMode.setItemText(8, _translate("MainWindow", "NA", None))
        self.cSettingsAcquisitionMode.setItemText(9, _translate("MainWindow", "Time delayed integration", None))
        self.groupBox_50.setTitle(_translate("MainWindow", "External Shutter", None))
        self.cSettingsShutterEx.setItemText(0, _translate("MainWindow", "Fully Auto", None))
        self.cSettingsShutterEx.setItemText(1, _translate("MainWindow", "Permanently Open", None))
        self.cSettingsShutterEx.setItemText(2, _translate("MainWindow", "Permanently Closed", None))
        self.groupBox_51.setTitle(_translate("MainWindow", "Internal Shutter", None))
        self.cSettingsShutter.setItemText(0, _translate("MainWindow", "Fully Auto", None))
        self.cSettingsShutter.setItemText(1, _translate("MainWindow", "Permanently Open", None))
        self.cSettingsShutter.setItemText(2, _translate("MainWindow", "Permanently Closed", None))
        self.gbImageParams.setTitle(_translate("MainWindow", "Image Parameters", None))
        self.groupBox_18.setTitle(_translate("MainWindow", "Horizontal Start", None))
        self.groupBox_17.setTitle(_translate("MainWindow", "Vertical Binning", None))
        self.groupBox_16.setTitle(_translate("MainWindow", "Horizontal Binning", None))
        self.groupBox_19.setTitle(_translate("MainWindow", "Horizontal End", None))
        self.groupBox_20.setTitle(_translate("MainWindow", "Vertical Start", None))
        self.groupBox_21.setTitle(_translate("MainWindow", "Vertical End", None))
        self.bSettingsApply.setText(_translate("MainWindow", "Apply", None))
        self.bSettingsCancel.setText(_translate("MainWindow", "Cancel", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Save settings", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Background Name", None))
        self.tBackgroundName.setText(_translate("MainWindow", "testBG", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Image Name", None))
        self.tImageName.setText(_translate("MainWindow", "test", None))
        self.groupBox_9.setTitle(_translate("MainWindow", "Save Directory", None))
        self.bSettingsDirectory.setText(_translate("MainWindow", "Choose..", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Temperature Control", None))
        self.groupBox_22.setTitle(_translate("MainWindow", "Current Temp", None))
        self.tSettingsCurrTemp.setText(_translate("MainWindow", "20", None))
        self.groupBox_23.setTitle(_translate("MainWindow", "Desired Temp", None))
        self.bSetTemp.setText(_translate("MainWindow", "Set Temperature", None))
        self.groupBox_24.setTitle(_translate("MainWindow", "Response", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSettings), _translate("MainWindow", "Settings", None))
        self.bSpecSetGr.setText(_translate("MainWindow", "Set", None))
        self.bSpecSetWl.setText(_translate("MainWindow", "Set", None))
        self.groupBox_33.setTitle(_translate("MainWindow", "Center wavelength", None))
        self.groupBox.setTitle(_translate("MainWindow", "Grating", None))
        self.groupBox_47.setTitle(_translate("MainWindow", "Current Wavelength", None))
        self.groupBox_49.setTitle(_translate("MainWindow", "GPIB", None))
        self.cSpecGPIB.setToolTip(_translate("MainWindow", "ASRL1", None))
        self.groupBox_48.setTitle(_translate("MainWindow", "Current Grating", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSpec), _translate("MainWindow", "Spectrometer", None))
        self.menuOther_Settings.setTitle(_translate("MainWindow", "Other Settings", None))
        self.menuLive_Series.setTitle(_translate("MainWindow", "Live Series", None))
        self.menuExperiment_Type.setTitle(_translate("MainWindow", "Experiment Type", None))
        self.mFileDoCRR.setText(_translate("MainWindow", "Do cosmic ray removal", None))
        self.mFileBreakTemp.setText(_translate("MainWindow", "Break temperature loop", None))
        self.mFileTakeContinuous.setText(_translate("MainWindow", "Take continuous", None))
        self.actionValue.setText(_translate("MainWindow", "value", None))
        self.mFileEnableAll.setText(_translate("MainWindow", "Enable Extra Settings", None))
        self.mFileSumSpectraUndo.setText(_translate("MainWindow", "Undo Last", None))
        self.mSeriesSum.setText(_translate("MainWindow", "Do Series", None))
        self.mSeriesUndo.setText(_translate("MainWindow", "Undo Last", None))
        self.fExpTypeHSG.setText(_translate("MainWindow", "HSG", None))
        self.fExpTypePL.setText(_translate("MainWindow", "PL", None))
        self.fExpTypeAbs.setText(_translate("MainWindow", "Abs", None))
        self.mFileFastExit.setText(_translate("MainWindow", "Exit without shutdown", None))
        self.fExpTypeTwo_Color_Abs.setText(_translate("MainWindow", "Two Color Abs", None))

from InstsAndQt.customQt import QINumberEdit
import resources_rc
