# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\FELLab\Documents\GitHub\EMCCD-psychic\UIs\TwoColorAbs.ui'
#
# Created: Wed Jan 13 16:26:02 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtCore.QCoreApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtCore.QCoreApplication.translate(context, text, disambig)

class Ui_TwoColorAbs(object):
    def setupUi(self, TwoColorAbs):
        TwoColorAbs.setObjectName("TwoColorAbs")
        TwoColorAbs.resize(624, 635)
        self.verticalLayout = QtWidgets.QVBoxLayout(TwoColorAbs)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitterAll = QtWidgets.QSplitter(TwoColorAbs)
        self.splitterAll.setOrientation(QtCore.Qt.Vertical)
        self.splitterAll.setObjectName("splitterAll")
        self.splitterTop = QtWidgets.QSplitter(self.splitterAll)
        self.splitterTop.setOrientation(QtCore.Qt.Horizontal)
        self.splitterTop.setObjectName("splitterTop")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.splitterTop)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_3.sizePolicy().hasHeightForWidth())
        self.tabWidget_3.setSizePolicy(sizePolicy)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.bCCDBack = QtWidgets.QPushButton(self.tab_3)
        self.bCCDBack.setObjectName("bCCDBack")
        self.gridLayout.addWidget(self.bCCDBack, 4, 0, 1, 1)
        self.groupBox_35 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_35.setFlat(True)
        self.groupBox_35.setObjectName("groupBox_35")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.groupBox_35)
        self.horizontalLayout_33.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.tEMCCDGain = QINumberEdit(self.groupBox_35)
        self.tEMCCDGain.setObjectName("tEMCCDGain")
        self.horizontalLayout_33.addWidget(self.tEMCCDGain)
        self.gridLayout.addWidget(self.groupBox_35, 4, 1, 1, 1)
        self.groupBox_38 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_38.setFlat(True)
        self.groupBox_38.setCheckable(False)
        self.groupBox_38.setObjectName("groupBox_38")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_38)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setContentsMargins(0, 10, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tCCDBGNum = QINumberEdit(self.groupBox_38)
        self.tCCDBGNum.setObjectName("tCCDBGNum")
        self.gridLayout_8.addWidget(self.tCCDBGNum, 0, 0, 1, 1)
        self.bProcessBackgroundSequence = QtWidgets.QToolButton(self.groupBox_38)
        self.bProcessBackgroundSequence.setText("")
        self.bProcessBackgroundSequence.setArrowType(QtCore.Qt.RightArrow)
        self.bProcessBackgroundSequence.setObjectName("bProcessBackgroundSequence")
        self.gridLayout_8.addWidget(self.bProcessBackgroundSequence, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_38, 4, 2, 1, 1)
        self.groupBox_34 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_34.setFlat(True)
        self.groupBox_34.setObjectName("groupBox_34")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.groupBox_34)
        self.horizontalLayout_32.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.tEMCCDExp = QFNumberEdit(self.groupBox_34)
        self.tEMCCDExp.setObjectName("tEMCCDExp")
        self.horizontalLayout_32.addWidget(self.tEMCCDExp)
        self.gridLayout.addWidget(self.groupBox_34, 3, 1, 1, 1)
        self.bCCDImage = QtWidgets.QPushButton(self.tab_3)
        self.bCCDImage.setObjectName("bCCDImage")
        self.gridLayout.addWidget(self.bCCDImage, 0, 0, 1, 1)
        self.bCCDReference = QtWidgets.QPushButton(self.tab_3)
        self.bCCDReference.setObjectName("bCCDReference")
        self.gridLayout.addWidget(self.bCCDReference, 3, 0, 1, 1)
        self.groupBox_42 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_42.setFlat(True)
        self.groupBox_42.setCheckable(False)
        self.groupBox_42.setObjectName("groupBox_42")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_42)
        self.gridLayout_12.setSpacing(0)
        self.gridLayout_12.setContentsMargins(0, 10, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.tSampleName = QtWidgets.QLineEdit(self.groupBox_42)
        self.tSampleName.setToolTip("")
        self.tSampleName.setStatusTip("")
        self.tSampleName.setWhatsThis("")
        self.tSampleName.setAccessibleName("")
        self.tSampleName.setAccessibleDescription("")
        self.tSampleName.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tSampleName.setText("")
        self.tSampleName.setObjectName("tSampleName")
        self.gridLayout_12.addWidget(self.tSampleName, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_42, 0, 1, 1, 1)
        self.groupBox_37 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_37.setFlat(True)
        self.groupBox_37.setCheckable(False)
        self.groupBox_37.setObjectName("groupBox_37")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_37)
        self.horizontalLayout_6.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.tCCDImageNum = QINumberEdit(self.groupBox_37)
        self.tCCDImageNum.setObjectName("tCCDImageNum")
        self.horizontalLayout_6.addWidget(self.tCCDImageNum)
        self.bProcessImageSequence = QtWidgets.QToolButton(self.groupBox_37)
        self.bProcessImageSequence.setText("")
        self.bProcessImageSequence.setArrowType(QtCore.Qt.RightArrow)
        self.bProcessImageSequence.setObjectName("bProcessImageSequence")
        self.horizontalLayout_6.addWidget(self.bProcessImageSequence)
        self.gridLayout.addWidget(self.groupBox_37, 0, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tCCDRefNum = QINumberEdit(self.groupBox)
        self.tCCDRefNum.setObjectName("tCCDRefNum")
        self.horizontalLayout.addWidget(self.tCCDRefNum)
        self.bProcessReferenceSequence = QtWidgets.QToolButton(self.groupBox)
        self.bProcessReferenceSequence.setText("")
        self.bProcessReferenceSequence.setArrowType(QtCore.Qt.RightArrow)
        self.bProcessReferenceSequence.setObjectName("bProcessReferenceSequence")
        self.horizontalLayout.addWidget(self.bProcessReferenceSequence)
        self.gridLayout.addWidget(self.groupBox, 3, 2, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox_Series = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_Series.setFlat(True)
        self.groupBox_Series.setObjectName("groupBox_Series")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_Series)
        self.horizontalLayout_2.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tCCDSeries = QtWidgets.QLineEdit(self.groupBox_Series)
        self.tCCDSeries.setObjectName("tCCDSeries")
        self.horizontalLayout_2.addWidget(self.tCCDSeries)
        self.horizontalLayout_5.addWidget(self.groupBox_Series)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_4.setFlat(True)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tSpectrumStep = QtWidgets.QLineEdit(self.groupBox_4)
        self.tSpectrumStep.setObjectName("tSpectrumStep")
        self.horizontalLayout_3.addWidget(self.tSpectrumStep)
        self.horizontalLayout_5.addWidget(self.groupBox_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.groupBox_46 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_46.setFlat(True)
        self.groupBox_46.setObjectName("groupBox_46")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout(self.groupBox_46)
        self.horizontalLayout_37.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.tCCDComments = QtWidgets.QTextEdit(self.groupBox_46)
        self.tCCDComments.setObjectName("tCCDComments")
        self.horizontalLayout_37.addWidget(self.tCCDComments)
        self.verticalLayout_2.addWidget(self.groupBox_46)
        self.tabWidget_3.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_52 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_52.setObjectName("horizontalLayout_52")
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.groupBox_43 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_43.setFlat(True)
        self.groupBox_43.setCheckable(False)
        self.groupBox_43.setObjectName("groupBox_43")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_43)
        self.gridLayout_13.setSpacing(0)
        self.gridLayout_13.setContentsMargins(0, 10, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.tCCDYMin = QtWidgets.QLineEdit(self.groupBox_43)
        self.tCCDYMin.setObjectName("tCCDYMin")
        self.gridLayout_13.addWidget(self.tCCDYMin, 0, 0, 1, 1)
        self.gridLayout_17.addWidget(self.groupBox_43, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_44.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.tCCDSampleTemp = QtWidgets.QLineEdit(self.groupBox_2)
        self.tCCDSampleTemp.setObjectName("tCCDSampleTemp")
        self.horizontalLayout_44.addWidget(self.tCCDSampleTemp)
        self.gridLayout_17.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_3.setFlat(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_15.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.tCCDLEDCurrent = QtWidgets.QLineEdit(self.groupBox_3)
        self.tCCDLEDCurrent.setObjectName("tCCDLEDCurrent")
        self.horizontalLayout_15.addWidget(self.tCCDLEDCurrent)
        self.gridLayout_17.addWidget(self.groupBox_3, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_17.addItem(spacerItem, 4, 0, 1, 1)
        self.groupBox_14 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_14.setFlat(True)
        self.groupBox_14.setObjectName("groupBox_14")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.groupBox_14)
        self.horizontalLayout_16.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.tCCDLEDTemp = QtWidgets.QLineEdit(self.groupBox_14)
        self.tCCDLEDTemp.setObjectName("tCCDLEDTemp")
        self.horizontalLayout_16.addWidget(self.tCCDLEDTemp)
        self.gridLayout_17.addWidget(self.groupBox_14, 3, 2, 1, 1)
        self.groupBox_44 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_44.setFlat(True)
        self.groupBox_44.setCheckable(False)
        self.groupBox_44.setObjectName("groupBox_44")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox_44)
        self.gridLayout_14.setSpacing(0)
        self.gridLayout_14.setContentsMargins(0, 10, 0, 0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.tCCDYMax = QtWidgets.QLineEdit(self.groupBox_44)
        self.tCCDYMax.setObjectName("tCCDYMax")
        self.gridLayout_14.addWidget(self.tCCDYMax, 0, 0, 1, 1)
        self.gridLayout_17.addWidget(self.groupBox_44, 1, 2, 1, 1)
        self.groupBox_45 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_45.setFlat(True)
        self.groupBox_45.setCheckable(False)
        self.groupBox_45.setObjectName("groupBox_45")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox_45)
        self.gridLayout_15.setSpacing(0)
        self.gridLayout_15.setContentsMargins(0, 10, 0, 0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.tCCDSlits = QtWidgets.QLineEdit(self.groupBox_45)
        self.tCCDSlits.setObjectName("tCCDSlits")
        self.gridLayout_15.addWidget(self.tCCDSlits, 0, 0, 1, 1)
        self.gridLayout_17.addWidget(self.groupBox_45, 0, 2, 1, 1)
        self.groupBox_17 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_17.setFlat(True)
        self.groupBox_17.setObjectName("groupBox_17")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.groupBox_17)
        self.horizontalLayout_19.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.tCCDLEDPower = QtWidgets.QLineEdit(self.groupBox_17)
        self.tCCDLEDPower.setObjectName("tCCDLEDPower")
        self.horizontalLayout_19.addWidget(self.tCCDLEDPower)
        self.gridLayout_17.addWidget(self.groupBox_17, 2, 2, 1, 1)
        self.groupBox_15 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_15.setFlat(True)
        self.groupBox_15.setObjectName("groupBox_15")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.groupBox_15)
        self.horizontalLayout_17.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.tCCDNIRPol = QtWidgets.QLineEdit(self.groupBox_15)
        self.tCCDNIRPol.setObjectName("tCCDNIRPol")
        self.horizontalLayout_17.addWidget(self.tCCDNIRPol)
        self.gridLayout_17.addWidget(self.groupBox_15, 2, 0, 1, 1)
        self.horizontalLayout_52.addLayout(self.gridLayout_17)
        self.tabWidget_3.addTab(self.tab_4, "")
        self.splitterImages = QtWidgets.QSplitter(self.splitterTop)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitterImages.sizePolicy().hasHeightForWidth())
        self.splitterImages.setSizePolicy(sizePolicy)
        self.splitterImages.setOrientation(QtCore.Qt.Vertical)
        self.splitterImages.setObjectName("splitterImages")
        self.gCCDImage = ImageViewWithPlotItemContainer(self.splitterImages)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.gCCDImage.sizePolicy().hasHeightForWidth())
        self.gCCDImage.setSizePolicy(sizePolicy)
        self.gCCDImage.setObjectName("gCCDImage")
        self.gCCDBack = ImageViewWithPlotItemContainer(self.splitterImages)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.gCCDBack.sizePolicy().hasHeightForWidth())
        self.gCCDBack.setSizePolicy(sizePolicy)
        self.gCCDBack.setObjectName("gCCDBack")
        self.gCCDBin = PlotWidget(self.splitterAll)
        self.gCCDBin.setObjectName("gCCDBin")
        self.layoutWidget = QtWidgets.QWidget(self.splitterAll)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_34.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.pCCD = QtWidgets.QProgressBar(self.layoutWidget)
        self.pCCD.setProperty("value", 0)
        self.pCCD.setObjectName("pCCD")
        self.horizontalLayout_34.addWidget(self.pCCD)
        self.lCCDProg = QtWidgets.QLabel(self.layoutWidget)
        self.lCCDProg.setObjectName("lCCDProg")
        self.horizontalLayout_34.addWidget(self.lCCDProg)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem1)
        self.groupBox_13 = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_13.setFlat(True)
        self.groupBox_13.setObjectName("groupBox_13")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_13)
        self.horizontalLayout_4.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tCCDFELPulses = QtWidgets.QLineEdit(self.groupBox_13)
        self.tCCDFELPulses.setReadOnly(True)
        self.tCCDFELPulses.setObjectName("tCCDFELPulses")
        self.horizontalLayout_4.addWidget(self.tCCDFELPulses)
        self.horizontalLayout_34.addWidget(self.groupBox_13)
        self.horizontalLayout_34.setStretch(0, 9)
        self.horizontalLayout_34.setStretch(1, 1)
        self.horizontalLayout_34.setStretch(2, 1)
        self.horizontalLayout_34.setStretch(3, 1)
        self.verticalLayout.addWidget(self.splitterAll)

        self.retranslateUi(TwoColorAbs)
        self.tabWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TwoColorAbs)

    def retranslateUi(self, TwoColorAbs):
        TwoColorAbs.setWindowTitle(_translate("TwoColorAbs", "Form", None))
        self.bCCDBack.setText(_translate("TwoColorAbs", "Take Background", None))
        self.groupBox_35.setTitle(_translate("TwoColorAbs", "Gain", None))
        self.tEMCCDGain.setText(_translate("TwoColorAbs", "1", None))
        self.groupBox_38.setTitle(_translate("TwoColorAbs", "Bg Number", None))
        self.tCCDBGNum.setText(_translate("TwoColorAbs", "0", None))
        self.groupBox_34.setTitle(_translate("TwoColorAbs", "Exp (s)", None))
        self.tEMCCDExp.setText(_translate("TwoColorAbs", "0.5", None))
        self.bCCDImage.setText(_translate("TwoColorAbs", "Take Image", None))
        self.bCCDReference.setText(_translate("TwoColorAbs", "Take Reference", None))
        self.groupBox_42.setTitle(_translate("TwoColorAbs", "Sample", None))
        self.groupBox_37.setTitle(_translate("TwoColorAbs", "Image Number", None))
        self.tCCDImageNum.setText(_translate("TwoColorAbs", "0", None))
        self.groupBox.setTitle(_translate("TwoColorAbs", "Ref Number", None))
        self.tCCDRefNum.setText(_translate("TwoColorAbs", "0", None))
        self.groupBox_Series.setTitle(_translate("TwoColorAbs", "Series", None))
        self.tCCDSeries.setToolTip(_translate("TwoColorAbs", "NIRP, NIRW, FELF, FELP, SLITS, SPECL", None))
        self.groupBox_4.setTitle(_translate("TwoColorAbs", "Spectrum step", None))
        self.groupBox_46.setTitle(_translate("TwoColorAbs", "Comments", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_3), _translate("TwoColorAbs", "Main Settings", None))
        self.groupBox_43.setTitle(_translate("TwoColorAbs", "Ymin", None))
        self.tCCDYMin.setText(_translate("TwoColorAbs", "0", None))
        self.groupBox_2.setTitle(_translate("TwoColorAbs", "Sample Temp", None))
        self.groupBox_3.setTitle(_translate("TwoColorAbs", "LED Current (mA)", None))
        self.tCCDLEDCurrent.setText(_translate("TwoColorAbs", "0", None))
        self.groupBox_14.setTitle(_translate("TwoColorAbs", "LED Temp", None))
        self.tCCDLEDTemp.setText(_translate("TwoColorAbs", "0", None))
        self.groupBox_44.setTitle(_translate("TwoColorAbs", "Ymax", None))
        self.tCCDYMax.setText(_translate("TwoColorAbs", "400", None))
        self.groupBox_45.setTitle(_translate("TwoColorAbs", "Slits", None))
        self.tCCDSlits.setText(_translate("TwoColorAbs", "0", None))
        self.groupBox_17.setTitle(_translate("TwoColorAbs", "LED Power (mW)", None))
        self.tCCDLEDPower.setText(_translate("TwoColorAbs", "0", None))
        self.groupBox_15.setTitle(_translate("TwoColorAbs", "NIR Pol", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_4), _translate("TwoColorAbs", "Other Settings", None))
        self.lCCDProg.setText(_translate("TwoColorAbs", "Done.", None))
        self.groupBox_13.setTitle(_translate("TwoColorAbs", "FEL Pulses", None))

from pyqtgraph import PlotWidget

from .ImageViewWithPlotItemContainer import ImageViewWithPlotItemContainer

from InstsAndQt.customQt import QINumberEdit, QFNumberEdit

